### ISSUE TITLE
Output as parquet to hdfs

### ISSUE THREAD

**Issue by xificurC** [linkedin/gobblin#1011]
Setting `writer.output.format=parquet` creates a `.parquet` file in hdfs but the file is still just plain text.

Running in standalone mode. Config:

```
job.name=GobblinKafkaParquet
job.group=GobblinKafka
job.description=Gobblin for parquet
job.lock.enabled=false

kafka.brokers=daup-kafka:9092

source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=parquet

data.publisher.type=gobblin.publisher.BaseDataPublisher

mr.job.max.mappers=1

metrics.reporting.file.enabled=true
metrics.log.dir=${env:GOBBLIN_WORK_DIR}/metrics
metrics.reporting.file.suffix=txt

bootstrap.with.offset=earliest

fs.uri=hdfs://daup-hadoop:9000
writer.fs.uri=hdfs://daup-hadoop:9000
state.store.fs.uri=hdfs://daup-hadoop:9000

mr.job.root.dir=/gobblin-kafka/working
state.store.dir=/gobblin-kafka/state-store
task.data.root.dir=/jobs/kafkaetl/gobblin/gobblin-kafka/task-data
data.publisher.final.dir=/gobblintest/job-output
```

Log output:

```
2016-05-23 10:32:08 GMT INFO  [main] org.quartz.impl.StdSchedulerFactory  1172 - Using default implementation for ThreadExecutor
2016-05-23 10:32:08 GMT INFO  [main] org.quartz.core.SchedulerSignalerImpl  61 - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2016-05-23 10:32:08 GMT INFO  [main] org.quartz.core.QuartzScheduler  240 - Quartz Scheduler v.2.2.3 created.
2016-05-23 10:32:08 GMT INFO  [main] org.quartz.simpl.RAMJobStore  155 - RAMJobStore initialized.
2016-05-23 10:32:08 GMT INFO  [main] org.quartz.core.QuartzScheduler  305 - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'LocalJobScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 3 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2016-05-23 10:32:08 GMT INFO  [main] org.quartz.impl.StdSchedulerFactory  1327 - Quartz scheduler 'LocalJobScheduler' initialized from specified file: '/home/gobblin/gobblin/dist/conf/quartz.properties'
2016-05-23 10:32:08 GMT INFO  [main] org.quartz.impl.StdSchedulerFactory  1331 - Quartz scheduler version: 2.2.3
2016-05-23 10:32:08 GMT INFO  [main] gobblin.runtime.app.ServiceBasedAppLauncher  144 - Starting the Gobblin application and all its associated Services
2016-05-23 10:32:08 GMT INFO  [JobScheduler STARTING] gobblin.scheduler.JobScheduler  146 - Starting the job scheduler
2016-05-23 10:32:08 GMT INFO  [JobScheduler STARTING] org.quartz.core.QuartzScheduler  575 - Scheduler LocalJobScheduler_$_NON_CLUSTERED started.
2016-05-23 10:32:08 GMT INFO  [JobScheduler STARTING] gobblin.scheduler.JobScheduler  365 - Scheduling locally configured jobs
2016-05-23 10:32:08 GMT INFO  [JobScheduler STARTING] gobblin.scheduler.JobScheduler  378 - Loaded 1 job configuration
2016-05-23 10:32:08 GMT WARN  [JobScheduler-0] org.apache.hadoop.util.NativeCodeLoader  62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] org.apache.hadoop.io.compress.CodecPool  181 - Got brand-new decompressor [.deflate]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] org.apache.hadoop.io.compress.CodecPool  181 - Got brand-new decompressor [.deflate]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] org.apache.hadoop.io.compress.CodecPool  181 - Got brand-new decompressor [.deflate]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] org.apache.hadoop.io.compress.CodecPool  181 - Got brand-new decompressor [.deflate]
2016-05-23 10:32:09 GMT WARN  [JobScheduler-0] gobblin.runtime.JobContext  260 - Property writer.staging.dir is deprecated. No need to use it if task.data.root.dir is specified.
2016-05-23 10:32:09 GMT WARN  [JobScheduler-0] gobblin.runtime.JobContext  277 - Property writer.output.dir is deprecated. No need to use it if task.data.root.dir is specified.
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ClustersNames  73 - no default cluster mapping found
2016-05-23 10:32:09 GMT INFO  [TaskExecutor STARTING] gobblin.runtime.TaskExecutor  119 - Starting the task executor
2016-05-23 10:32:09 GMT INFO  [LocalTaskStateTracker STARTING] gobblin.runtime.AbstractTaskStateTracker  64 - Starting the task state tracker
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@2b4b0bb6[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@2b4b0bb6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.source.extractor.extract.kafka.KafkaWrapper$KafkaOldAPI  241 - Fetching topic metadata from broker daup-kafka:9092
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@6c4613a2[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:09 GMT INFO  [pool-19-thread-1] gobblin.source.extractor.extract.kafka.KafkaSource  369 - Created workunit for partition test:0: lowWatermark=25927, highWatermark=26032, range=105
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@6c4613a2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.source.extractor.extract.kafka.KafkaSource  129 - Created workunits for 1 topics in 0 seconds
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaAvgRecordTimeBasedWorkUnitSizeEstimator  135 - Estimated avg time to pull a record for topic test is 2.038012 milliseconds
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaAvgRecordTimeBasedWorkUnitSizeEstimator  145 - For all topics not pulled in the previous run, estimated avg time to pull a record is 2.038011695906433 milliseconds
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  293 - MultiWorkUnit 0: estimated load=64.417778, partitions=[[test:0]]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  279 - Min load of multiWorkUnit = 64.417778; Max load of multiWorkUnit = 64.417778; Diff = 0.000000%
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@1a10dd9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@1a10dd9[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.runtime.AbstractJobLauncher  276 - Starting job job_GobblinKafkaParquet_1463999528500
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@20a8fa1c[Shutting down, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@20a8fa1c[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.runtime.TaskExecutor  152 - Executing task task_GobblinKafkaParquet_1463999528500_0
2016-05-23 10:32:09 GMT INFO  [JobScheduler-0] gobblin.runtime.local.LocalJobLauncher  115 - Waiting for submitted tasks of job job_GobblinKafkaParquet_1463999528500 to complete...
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.runtime.TaskExecutor  184 - Submitting fork 0 of task task_GobblinKafkaParquet_1463999528500_0
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  185 - Pulling topic test
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  205 - Pulling partition test:0 from offset 25927 to 26032, range=105
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  172 - Finished pulling partition test:0
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  160 - Finished pulling topic test
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.runtime.Task  176 - Extracted 105 data records
2016-05-23 10:32:09 GMT INFO  [TaskExecutor-0] gobblin.runtime.Task  177 - Row quality checker finished with results: 
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.publisher.TaskPublisher  48 - All components finished successfully, checking quality tests
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.publisher.TaskPublisher  50 - All required test passed for this task passed.
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.publisher.TaskPublisher  52 - Cleanup for task publisher executed successfully.
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.runtime.Fork  261 - Committing data for fork 0 of task task_GobblinKafkaParquet_1463999528500_0
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.writer.FsDataWriter  172 - Moving data from /home/gobblin/gobblin/work-dir/task-staging/test/part.task_GobblinKafkaParquet_1463999528500_0.parquet to /home/gobblin/gobblin/work-dir/task-output/test/part.task_GobblinKafkaParquet_1463999528500_0.parquet
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@2fcaf231[Terminated, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@2fcaf231[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  261 - Actual high watermark for partition test:0=26032, expected=26032
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  270 - Avg time to pull a record for partition test:0 = 1.466667 milliseconds
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.runtime.Task  289 - publish.data.at.job.level is true. Will publish data at the job level.
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.runtime.local.LocalJobLauncher  132 - All tasks of job job_GobblinKafkaParquet_1463999528500 have completed
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.runtime.JobContext  324 - 1 more tasks of job job_GobblinKafkaParquet_1463999528500 have completed
2016-05-23 10:32:10 GMT INFO  [TaskExecutor-0] gobblin.runtime.local.LocalTaskStateTracker  117 - Task task_GobblinKafkaParquet_1463999528500_0 completed in 1287ms with state SUCCESSFUL
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.runtime.JobContext  397 - Committing dataset  of job job_GobblinKafkaParquet_1463999528500 with commit policy COMMIT_ON_FULL_SUCCESS and state SUCCESSFUL
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.publisher.BaseDataPublisher  310 - Moving hdfs://daup-hadoop:9000/home/gobblin/gobblin/work-dir/task-output/test/part.task_GobblinKafkaParquet_1463999528500_0.parquet to /gobblintest/job-output/test/part.task_GobblinKafkaParquet_1463999528500_0.parquet
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@1468a28e[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@1468a28e[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.runtime.JobContext  568 - Persisting dataset state for dataset 
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] gobblin.runtime.FsDatasetStateStore  219 - Persisting job_GobblinKafkaParquet_1463999528500.jst to the job state store
2016-05-23 10:32:10 GMT INFO  [JobScheduler-0] org.apache.hadoop.io.compress.CodecPool  153 - Got brand-new compressor [.deflate]
2016-05-23 10:32:11 GMT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  213 - Cleaning up staging directory /home/gobblin/gobblin/work-dir/task-staging/test
2016-05-23 10:32:11 GMT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  219 - Cleaning up output directory /home/gobblin/gobblin/work-dir/task-output/test
2016-05-23 10:32:11 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@40a695c6[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:11 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@40a695c6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:11 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@2a48491b[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:11 GMT INFO  [JobScheduler-0] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@2a48491b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor  134 - Stopping the task executor
2016-05-23 10:32:11 GMT INFO  [LocalTaskStateTracker STOPPING] gobblin.runtime.AbstractTaskStateTracker  69 - Stopping the task state tracker
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@19839e35[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:11 GMT INFO  [LocalTaskStateTracker STOPPING] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@502fd7d6[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@19839e35[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:11 GMT INFO  [LocalTaskStateTracker STOPPING] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@502fd7d6[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@17446375[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@17446375[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@137bf545[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-05-23 10:32:11 GMT INFO  [TaskExecutor STOPPING] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@137bf545[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
```

**Comment by sahilTakiar** [comment]
Unfortunately, the configuration key `writer.output.format` is mis-leading. It only controls the file name suffix.

If you want to write data in Parquet format, you can use the following guide to do so: http://gobblin.readthedocs.io/en/latest/case-studies/Writing-ORC-Data/ - the guide was written for writing ORC data, but it should be applicable for Parquet data (simply replace ORC with Parquet in the configuration keys).

**Comment by ashish211981** [comment]
I tried replacing ORC with Parquet. However, it's not working.

**Comment by ashish211981** [comment]
I think we need to change the class ( gobblin.converter.serde.HiveSerDeConverter ) as well to write in parquet.

**Comment by abti** [comment]
@xificurC @ashish211981 Can you please share your logs and pull file for Parquet?

**Comment by sidarthakarna** [comment]
@abti I am getting NPE when trying to store the data in parquet. Following is the excerpt from the log observed.

```
2016-08-08 11:02:20 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper$JSchLogger  333 - SSH_MSG_SERVICE_REQUEST sent
2016-08-08 11:02:20 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper$JSchLogger  333 - SSH_MSG_SERVICE_ACCEPT received
2016-08-08 11:02:20 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper$JSchLogger  333 - Authentications that can continue: publickey,password
2016-08-08 11:02:20 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper$JSchLogger  333 - Next authentication method: publickey
2016-08-08 11:02:20 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper$JSchLogger  333 - Authentication succeeded (publickey).
2016-08-08 11:02:20 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper  186 - Finished connecting to source
2016-08-08 11:02:20 UTC ERROR [TaskRetryExecutor-0] gobblin.runtime.Task  266 - Task task_SftpExampleJob_1470654137436_0 failed
java.lang.NullPointerException
        at org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe.initialize(ParquetHiveSerDe.java:111)
        at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:72)
        at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:57)
        at gobblin.instrumented.converter.InstrumentedConverterDecorator.init(InstrumentedConverterDecorator.java:46)
        at gobblin.runtime.TaskContext.getConverters(TaskContext.java:199)
        at gobblin.runtime.TaskContext.getConverters(TaskContext.java:170)
        at gobblin.runtime.Task.run(Task.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Looking at the code in ParquetHiveSerDe.java, following seems to be the issue:
```java
  public final void initialize(final Configuration conf, final Properties tbl) throws SerDeException {

    final TypeInfo rowTypeInfo;
    final List<String> columnNames;
    final List<TypeInfo> columnTypes;
    // Get column names and sort order
    final String columnNameProperty = tbl.getProperty(IOConstants.COLUMNS);
    final String columnTypeProperty = tbl.getProperty(IOConstants.COLUMNS_TYPES);

    if (columnNameProperty.length() == 0) {
      columnNames = new ArrayList<String>();
    } 
```
columnNameProperty is set to Null. 

OrcSerDe seems to be handling nulls.
```java
  public void initialize(Configuration conf, Properties table) {
    // Read the configuration parameters
    String columnNameProperty = table.getProperty("columns");
    // NOTE: if "columns.types" is missing, all columns will be of String type
    String columnTypeProperty = table.getProperty("columns.types");

    // Parse the configuration parameters
    ArrayList<String> columnNames = new ArrayList<String>();
    if (columnNameProperty != null && columnNameProperty.length() > 0) {
      for (String name : columnNameProperty.split(",")) {
        columnNames.add(name);
      }
    }
    if (columnTypeProperty == null) {
      // Default type: all string
      StringBuilder sb = new StringBuilder();
      for (int i = 0; i < columnNames.size(); i++) {
        if (i > 0) {
          sb.append(":");
        }
        sb.append("string");
      }
      columnTypeProperty = sb.toString();
    }
```

HTH

**Comment by ipostanogov** [comment]
@abti @sahilTakiar 

I'm having the same issue. Here is an example.

I'm creating a single record using Kafka REST Proxy
```
curl -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json" --data '{"value_schema":"{\"type\":\"record\",\"name\":\"somertype\",\"fields\":[{\"name\":\"d_0\",\"type\":[\"string\",\"null\"]},{\"name\":\"i_1\",\"type\":[\"string\",\"null\"]},{\"name\":\"i_2\",\"type\":[\"string\",\"null\"]},{\"name\":\"e_3\",\"type\":[\"string\",\"null\"]},{\"name\":\"dt_4\",\"type\":[\"string\",\"null\"]}]}","records":[{"value":{"i_1":{"string":"-1070468553"},"e_3":{"string":"full-time_moleculeZSIJ"},"i_2":{"string":"1091131991"},"dt_4":{"string":"2007-12-23"},"d_0":{"string":"0.04668324195223028"}}}]}' "http://cluster-kafka-777-m:8082/topics/pub_dev_test_hdfs"
```
Then I create a pull
```
job.name=JN1-cluster-kafka-777
job.group=JG1-cluster-kafka-777
job.description=Desc
job.schedule=0 * * * * ?

#job.disabled=true

source.class=gobblin.source.extractor.extract.kafka.KafkaDeserializerSource

topic.whitelist=pub_dev_test_hdfs

kafka.deserializer.type=CONFLUENT_AVRO
kafka.schema.registry.url=http://cluster-kafka-777-m:8081

zookeeper.connect=127.0.0.1:2181
kafka.brokers=cluster-kafka-777-w-0:9092,cluster-kafka-777-w-1:9092
mr.job.max.mappers=1
bootstrap.with.offset=earliest

converter.classes=gobblin.converter.avro.AvroRecordToAvroWritableConverter,gobblin.converter.serde.HiveSerDeConverter

avro.schema.literal={"type":"record","name":"somertype","fields":[{"name":"d_0","type":["string","null"]},{"name":"i_1","type":["string","null"]},{"name":"i_2","type":["string","null"]},{"name":"e_3","type":["string","null"]},{"name":"dt_4","type":["string","null"]}]}

serde.deserializer.type=AVRO
serde.serializer.type=PARQUET

writer.builder.class=gobblin.writer.HiveWritableHdfsDataWriterBuilder
writer.output.format=PARQUET

data.publisher.type=gobblin.publisher.BaseDataPublisher
```

Then in logs I have
```
2016-10-29 06:25:01 UTC INFO  [TaskExecutor-0] io.confluent.common.config.AbstractConfig  135 - KafkaAvroDeseria
lizerConfig values: 
        schema.registry.url = [http://cluster-kafka-777-m:8081]
        max.schemas.per.subject = 1000
        specific.avro.reader = false

2016-10-29 06:25:01 UTC ERROR [TaskExecutor-0] gobblin.runtime.Task  266 - Task task_JN1-cluster-kafka-777_1477722300046_0 failed
java.lang.NullPointerException
        at org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe.initialize(ParquetHiveSerDe.java:111)
        at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:72)
        at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:57)
        at gobblin.instrumented.converter.InstrumentedConverterDecorator.init(InstrumentedConverterDecorator.java:46)
        at gobblin.runtime.TaskContext.getConverters(TaskContext.java:199)
        at gobblin.runtime.TaskContext.getConverters(TaskContext.java:170)
        at gobblin.runtime.Task.run(Task.java:129)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-10-29 06:25:01 UTC INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  261 - Actual high watermark for partition pub_dev_test_hdfs:0=0, expected=1
2016-10-29 06:25:01 UTC INFO  [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  273 - Avg time to pull a record for partition pub_dev_test_hdfs:0 not recorded
2016-10-29 06:25:01 UTC INFO  [TaskExecutor-0] gobblin.runtime.Task  289 - publish.data.at.job.level is true. Wi
ll publish data at the job level.
2016-10-29 06:25:01 UTC INFO  [TaskExecutor-0] gobblin.runtime.TaskExecutor  205 - Scheduled retry of failed tas
k task_JN1-cluster-kafka-777_1477722300046_0 to run in 0 seconds
2016-10-29 06:25:01 UTC INFO  [TaskRetryExecutor-0] io.confluent.common.config.AbstractConfig  135 - KafkaAvroDe
serializerConfig values: 
        schema.registry.url = [http://cluster-kafka-777-m:8081]
        max.schemas.per.subject = 1000
        specific.avro.reader = false
2016-10-29 06:25:01 UTC ERROR [TaskRetryExecutor-0] gobblin.runtime.Task  266 - Task task_JN1-cluster-kafka-777_
1477722300046_0 failed
java.lang.NullPointerException
        at org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe.initialize(ParquetHiveSerDe.java:111)
        at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:72)
        at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:57)
        at gobblin.instrumented.converter.InstrumentedConverterDecorator.init(InstrumentedConverterDecorator.jav
a:46)
        at gobblin.runtime.TaskContext.getConverters(TaskContext.java:199)
        at gobblin.runtime.TaskContext.getConverters(TaskContext.java:170)
        at gobblin.runtime.Task.run(Task.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolEx
ecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.
java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-10-29 06:25:01 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  261 -
 Actual high watermark for partition pub_dev_test_hdfs:0=0, expected=1
2016-10-29 06:25:01 UTC INFO  [TaskRetryExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor  273 -
 Avg time to pull a record for partition pub_dev_test_hdfs:0 not recorded
2016-10-29 06:25:01 UTC INFO  [TaskRetryExecutor-0] gobblin.runtime.Task  289 - publish.data.at.job.level is tru
e. Will publish data at the job level.
2016-10-29 06:25:01 UTC INFO  [TaskRetryExecutor-0] gobblin.runtime.TaskExecutor  205 - Scheduled retry of faile
d task task_JN1-cluster-kafka-777_1477722300046_0 to run in 300 seconds
```

P.S. Kafka 0.10.0.1, Gobblin 0.8.0, Google Dataproc image v.1.1

**Comment by abti** [comment]
This should be fixed now with @aditya1105 PR. Please reopen if still an issue.
