### ISSUE TITLE
Gobblin 0.7.0Build failed 

### ISSUE THREAD

**Issue by darionyaphet** [linkedin/gobblin#1018]
I download gobblin-gobblin_0.7.0 and running `./gradlew build --debug`  found a exception 

```
Changing state to: FAILED
Process 'command 'git'' finished with exit value 128 (state: FAILED)
Timing: Running the build script took 1.069 secs

FAILURE: Build failed with an exception.

* Where:
Build file '/home/maintain/darion/gobblin-gobblin_0.7.0/build.gradle' line: 101

* What went wrong:
A problem occurred evaluating root project 'gobblin-gobblin_0.7.0'.
> Process 'command 'git'' finished with non-zero exit value 128

* Exception is:
org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'gobblin-gobblin_0.7.0'.
   at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:54)
   at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:152)
   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:40)
   at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
   at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
   at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
   at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:493)
   at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:80)
   at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:28)
   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:142)
   at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:113)
   at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:81)
   at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:64)
   at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
   at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:35)
   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:45)
   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
   at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:42)
   at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
   at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
   at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.ReturnResult.execute(ReturnResult.java:34)
   at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
   at org.gradle.launcher.daemonution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
   at org.gradle.launcher.daemonution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
   at org.gradle.launcher.daemonution.proceed(DaemonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.ForwardClieBuROR] [org.gradle.BuildExceptionReporter]     at org.gradle.launc [r.daemon.server.exec.ForwardClientInput$2.call(ForwardClientIncut.java:71)
   at org.gradle.launcher.daemonution.proceed(DaemonCommadEExecution.java:125)
   at org.gradle.launcher.daemon.server.exec.Forwa:dClientInput$2.call(ForwardClientInput.java:71)
   at org.gradle.launcuer.daemonution.proceed(DaemonCommandExecution.java:125)
emon.server.exe.launcher.daemon.server.exec.ForwardClientInput$2.call(Forwa:1ClientInput.java:71)
   at org.gradle.launcher.daemonu  tion.proceed(DaitonCommandExecution.java:125)
   at org.gradle.launcher.daemon.server.ncec.ForwardClieBuROR] [org.gradle.BuildExceptionReporter]     at teCoordinator.java:186)
```

`Not a git repository`  seems should be a git repo ?

**Comment by chavdar** [comment]
How did you get the source? git clone?

The build does expect a git repository. If it is not, try running
"./gradlew -Pversion=0.7.0 build"

**Comment by abti** [comment]
@darionyaphet Were you able to build?

**Comment by darionyaphet** [comment]
@chavdar @abti I download the release package and building failed . But I can build from source code copy from git repo .

**Comment by chavdar** [comment]
Can you try building the release source code package with "./gradlew
-Pversion=0.70"  ?

If version is unspecified, the build script tries to derive it from the git
repo.

**Comment by darionyaphet** [comment]
@chavdar   "./gradlew clean build -Pversion=0.70"  running SUCC 👍 .
