### ISSUE TITLE
JobHistoryStore data too long for column

### ISSUE THREAD

**Issue by hilljb** [linkedin/gobblin#1075]
In the initial migration in gobblin-metastore/src/main/resources/db/migration, the job and task properties tables definitions have property_key defined as a varchar(128). This should be upped (I'm using 512) as it can lead to the following error, which not only stops the initial job from running... but the resulting partial job data placed into the db will cause errors in future attempts to run the job as well, even after the columns in question are modified. I had to delete rows from the job_execution table in order to have the job succeed.

```
2016-06-28 18:15:38 UTC ERROR [TaskExecutor-1] gobblin.metastore.database.DatabaseJobHistoryStoreV100  249 - Failed to put a new job execution information record
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'property_key' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3876)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.updateProperty(DatabaseJobHistoryStoreV100.java:518)
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.put(DatabaseJobHistoryStoreV100.java:239)
        at gobblin.metastore.DatabaseJobHistoryStore.put(DatabaseJobHistoryStore.java:64)
        at gobblin.runtime.JobContext.storeJobExecutionInfo(JobContext.java:315)
        at gobblin.runtime.JobContext.handleNewTaskCompletionEvent(JobContext.java:326)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
        at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
        at com.google.common.eventbus.EventBus.post(EventBus.java:267)
        at gobblin.runtime.local.LocalTaskStateTracker.onTaskCompletion(LocalTaskStateTracker.java:114)
        at gobblin.runtime.Task.run(Task.java:260)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)



2016-06-28 18:15:38 UTC ERROR [TaskExecutor-8] gobblin.metastore.database.DatabaseJobHistoryStoreV100  249 - Failed to put a new job execution information record
com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'property_key' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3876)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.updateProperty(DatabaseJobHistoryStoreV100.java:518)
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.put(DatabaseJobHistoryStoreV100.java:239)
        at gobblin.metastore.DatabaseJobHistoryStore.put(DatabaseJobHistoryStore.java:64)
        at gobblin.runtime.JobContext.storeJobExecutionInfo(JobContext.java:315)
        at gobblin.runtime.JobContext.handleNewTaskCompletionEvent(JobContext.java:326)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
        at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
        at com.google.common.eventbus.EventBus.post(EventBus.java:267)
        at gobblin.runtime.local.LocalTaskStateTracker.onTaskCompletion(LocalTaskStateTracker.java:114)
        at gobblin.runtime.Task.run(Task.java:260)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-06-28 18:15:38 UTC ERROR [TaskExecutor-8] gobblin.runtime.JobContext  317 - Failed to write job execution information to the job history store: java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'property_key' at row 1
java.io.IOException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'property_key' at row 1
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.put(DatabaseJobHistoryStoreV100.java:257)
        at gobblin.metastore.DatabaseJobHistoryStore.put(DatabaseJobHistoryStore.java:64)
        at gobblin.runtime.JobContext.storeJobExecutionInfo(JobContext.java:315)
        at gobblin.runtime.JobContext.handleNewTaskCompletionEvent(JobContext.java:326)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
        at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
        at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
        at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
        at com.google.common.eventbus.EventBus.post(EventBus.java:267)
        at gobblin.runtime.local.LocalTaskStateTracker.onTaskCompletion(LocalTaskStateTracker.java:114)
        at gobblin.runtime.Task.run(Task.java:260)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'property_key' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3876)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2551)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1861)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2073)
        at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2009)
        at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5094)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1994)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate(DelegatingPreparedStatement.java:105)
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.updateProperty(DatabaseJobHistoryStoreV100.java:518)
        at gobblin.metastore.database.DatabaseJobHistoryStoreV100.put(DatabaseJobHistoryStoreV100.java:239)
        ... 17 more
```

**Comment by sahilTakiar** [comment]
Do you know what property is actually causing this? I don't think we have any properties longer than 128 characters, but I could be wrong.

@kadaan have you ever seen this happen?

**Comment by kadaan** [comment]
The property value column can be longer than 128. For example the file-based-snapshot can be really long.

**Comment by abti** [comment]
@hilljb Can you please open a PR with the changes you made?

**Comment by hilljb** [comment]
See PR #1125

**Comment by abti** [comment]
Merged the PR
