### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.hadoop.yarn.client.ClientRMProxy.getRMDelegationTokenService

### ISSUE THREAD

**Issue by andytlim** [linkedin/gobblin#1200]
Hi,

I am getting the below issue when running /bin/gobblin-mapreduce.sh. 

I am using hadoop-yarn-common-2.6.0-cdh5.7.0.jar and the method should be available.

2016-08-12 11:57:58 EDT ERROR [main] gobblin.runtime.AbstractJobLauncher  321 - Failed to launch and run job job_PullFromWikipedia_1471017474587: java.lang.NoSuchMethodError: org.apache.hadoop.yarn.client.ClientRMProxy.getRMDelegationTokenService(Lorg/apache/hadoop/conf/Configuration;)Lorg/apache/hadoop/io/Text;
java.lang.NoSuchMethodError: org.apache.hadoop.yarn.client.ClientRMProxy.getRMDelegationTokenService(Lorg/apache/hadoop/conf/Configuration;)Lorg/apache/hadoop/io/Text;
        at org.apache.hadoop.mapred.ResourceMgrDelegate.getRMDelegationTokenService(ResourceMgrDelegate.java:165)
        at org.apache.hadoop.mapred.YARNRunner.addHistoryToken(YARNRunner.java:192)
        at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:282)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
        at gobblin.runtime.mapredu

**Comment by andytlim** [comment]
Is there a way to override the hadoop jar files, just to verify that's the issue?

A

**Comment by andytlim** [comment]
I have this listed in the /bin/gobblin-mapreduce.sh file as well:

# Honor Gobblin dependencies
export HADOOP_USER_CLASSPATH_FIRST=true
export HADOOP_CLASSPATH=$GOBBLIN_DEP_JARS:$HADOOP_CLASSPATH

I am using the Gobblin release http://linkedin.github.io/gobblin/release/2016/05/17/release-0.7.0.html

This should be picking up the Gobblin dependencies instead of the hadoop right? Unless the release lib jars are actually incorrect.

**Comment by lbendig** [comment]
I guess it's because the Gobblin release is built against vanilla Hadoop 2.3.0 but you are using a different version from Cloudera. Did you try to build Gobblin from source using the same Hadoop version you have?
The snippet you mentioned is for picking up user specific jars (using --jars) and putting them first on the classpath before submitting the job.

**Comment by andytlim** [comment]
I had some proxy issues with the source earlier so I tried to use the release. I see what you mean though. While attempting to build from source, I get this error now:

./gradlew clean build -PhadoopVersion=2.6.0-cdh5.7.0 

C:\Users\limandy\Documents\build\gobblin\build\gobblin-rest-server\classes\main
C:\Users\limandy\Documents\build\gobblin\build\gobblin-rest-server\resources\mai
n
C:\Users\limandy\Documents\build\gobblin\build\resource\classes\main
C:\Users\limandy\Documents\build\gobblin\build\resource\resources\main

FAILURE: Build failed with an exception.

* What went wrong:
Task '.6.0' not found in root project 'gobblin'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --info or --debug o
ption to get more log output.

* Exception is:
org.gradle.execution.TaskSelectionException: Task '.6.0' not found in root proje
ct 'gobblin'.
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:69)
        at org.gradle.execution.commandline.CommandLineTaskParser.parseTasks(Com
mandLineTaskParser.java:41)
        at org.gradle.execution.TaskNameResolvingBuildConfigurationAction.config
ure(TaskNameResolvingBuildConfigurationAction.java:45)
        at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecu
ter.java:42)
        at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
ter.java:48)
        at org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.co
nfigure(ExcludedTaskFilteringBuildConfigurationAction.java:46)
        at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecu
ter.java:42)
        at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
ter.java:48)
        at org.gradle.execution.DefaultTasksBuildExecutionAction.configure(Defau
ltTasksBuildExecutionAction.java:38)
        at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecu
ter.java:42)
        at org.gradle.execution.DefaultBuildExecuter.access$100(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
ter.java:48)
        at org.gradle.execution.ProjectEvaluatingAction.configure(ProjectEvaluat
ingAction.java:52)
        at org.gradle.execution.DefaultBuildExecuter.configure(DefaultBuildExecu
ter.java:42)
        at org.gradle.execution.DefaultBuildExecuter.select(DefaultBuildExecuter
.java:35)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:155)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:113)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:81)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:64)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.jav
a:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:35)

**Comment by lbendig** [comment]
I've just tried under linux, worked fine:
`./gradlew clean build -PhadoopVersion=2.6.0-cdh5.7.0 -Pversion=0.7.0 -x test`

**Comment by andytlim** [comment]
I still get the same error above when using Windows :(. Do you think it has to do with how the files are being pulled in on windows? Or small command line differences I may be not considering.

**Comment by lbendig** [comment]
Sorry, I have no experience building it under Windows..

2016-08-12 23:49 GMT+02:00 Andy Lim <notifications@github.com>:

**Comment by andytlim** [comment]
Np. I think this is the route I want to go, so I'll play around with it and see but if anyone sees this that can also run on windows and let me know if I'm just missing something simple--let me know.

Thanks

**Comment by bit1129** [comment]
When gobblin kicks off a MR job using hadoop jar command, it will first copy the jars in gobblin-dist/lib on the classpath, the gobblin-dist/lib contains the hadoop common and hadoop client jars, which I think is incorrect. When using hadoop jar command to kick off a MR job, there is no need to include the hadoop common and client jars on the classpath.
