### ISSUE TITLE
Gobblin MapReduce Deployment Fails

### ISSUE THREAD

**Issue by geek311** [linkedin/gobblin#1209]
I am trying to run Gobblin on MapReduce. In my NameNode gobblin-dist folder I am doing this - [mike@name1 gobblin-dist]$ bin/gobblin-mapreduce.sh --projectversion 0.6.2-861-g18a135e --conf ../work_dir/wikipedia.pull

I have added my hdfs uri properties in conf/gobblin-mapreduce.properties and also set all env vars like GOBBLIN_WORK_DIR etc. Standalone deployment works fine.

However MapReduce fails with this -
Exception in thread "main" gobblin.runtime.JobException: Job job_PullFromWikipedia_1471397156942 failed
        at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:363)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.launchJob(CliMRJobLauncher.java:84)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:61)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:106)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

Can someone please help?

**Comment by sahilTakiar** [comment]
This is a generic exception, indicating that one of the map tasks in the MR job failed. You need to check the logs of the map tasks that failed and look for the exception that caused the failure.

Typically, you can get all the map tasks logs by running `yarn logs -applicationId [app-id]`
