### ISSUE TITLE
java.io.IOException: Filesystem closed

### ISSUE THREAD

**Issue by jinhyukchang** [linkedin/gobblin#1219]
It seems recent change (8/14) on HadoopFsHelper closes file system (which is shared within JVM) where Launcher fails while it's trying to write task state into file system. If there's no benefit closing file system -- couldn't find what it does from their java doc, and some threads recommend not closing it as it breaks others using FileSystem.get -- we can leave it open, or we can use FileSystem.newInstance instead of FileSystem.get.

https://github.com/linkedin/gobblin/pull/1204

https://github.com/linkedin/gobblin/commit/342d20b1dbe9f1f83fe53c6ee0299c04bb9d71b8#diff-f6b4e6837a023e738b2538aa22b84e8dR170

2016-08-19 14:13:25,021 INFO [TaskExecutor-0] gobblin.runtime.Task: publish.data.at.job.level is true. Will publish data at the job level.
2016-08-19 14:13:25,022 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: All assigned tasks of job job_connectorJobTypeTests_gobblinTest-mySqlToHdfs_1471641185829 have completed in container attempt_1461347166530_0447_m_000000_0
2016-08-19 14:13:25,022 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: Writing task state for task task_connectorJobTypeTests_gobblinTest-mySqlToHdfs_1471641185829_0
2016-08-19 14:13:25,022 INFO [TaskExecutor-0] gobblin.runtime.mapreduce.MRTaskStateTracker: Task task_connectorJobTypeTests_gobblinTest-mySqlToHdfs_1471641185829_0 completed in 3164ms with state SUCCESSFUL
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Stopping the task executor
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@25277b2[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@25277b2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Attempting to shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@2be091f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Successfully shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@2be091f[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@2fdf105[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-08-19 14:13:25,025 INFO [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor: Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@2fdf105[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 1]
2016-08-19 14:13:25,025 INFO [MRTaskStateTracker STOPPING] gobblin.runtime.mapreduce.MRTaskStateTracker: Stopping the task state tracker
2016-08-19 14:13:25,025 INFO [MRTaskStateTracker STOPPING] gobblin.runtime.mapreduce.MRTaskStateTracker: Attempting to shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@759598a[Shutting down, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-08-19 14:13:25,026 INFO [MRTaskStateTracker STOPPING] gobblin.runtime.mapreduce.MRTaskStateTracker: Successfully shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@759598a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-08-19 14:13:25,029 INFO [main] org.apache.hadoop.mapred.MapTask: Ignoring exception during close for org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader@1cb3ec38
java.io.IOException: Filesystem closed
at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:689)
at org.apache.hadoop.hdfs.DFSInputStream.close(DFSInputStream.java:617)
at java.io.FilterInputStream.close(FilterInputStream.java:181)
at org.apache.hadoop.util.LineReader.close(LineReader.java:150)
at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.close(LineRecordReader.java:193)
at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.close(MapTask.java:500)
at org.apache.hadoop.mapred.MapTask.closeQuietly(MapTask.java:1973)
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:773)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)
2016-08-19 14:13:25,031 WARN [main] org.apache.hadoop.security.UserGroupInformation: PriviledgedActionException as:jnchang (auth:SIMPLE) cause:java.io.IOException: Filesystem closed
2016-08-19 14:13:25,031 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.io.IOException: Filesystem closed
at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:689)
at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1744)
at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1112)
at org.apache.hadoop.hdfs.DistributedFileSystem$17.doCall(DistributedFileSystem.java:1108)
at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1108)
at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1399)
at gobblin.metastore.FsStateStore.put(FsStateStore.java:135)
at gobblin.runtime.AbstractJobLauncher.runWorkUnits(AbstractJobLauncher.java:644)
at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.run(MRJobLauncher.java:597)
at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
at java.security.AccessController.doPrivileged(Native Method)
at javax.security.auth.Subject.doAs(Subject.java:422)
at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)

**Comment by ibuenros** [comment]
Hi,
You are right about the issue of closing FileSystems, and we've seen it in
other places in Gobblin recently. Unfortunately, sometimes it is necessary
to close the FileSystem, for example when pulling from FTP / SFTP. The
newInstance approach seems like a good solution to me, given that this fs
gets instantiated only once.
Would you want to make the change and submit a PR?
Thanks!
Issac

**Comment by jinhyukchang** [comment]
@ibuenros No problem. I can post a PR probably by EOD.

Thanks,
Jin

**Comment by jinhyukchang** [comment]
PR: https://github.com/linkedin/gobblin/pull/1221
