### ISSUE TITLE
BUILD FAILED in gobblin

### ISSUE THREAD

**Issue by Tracy6465** [linkedin/gobblin#1241]
when I  using the ./gradlew clean build -PhadoopVersion=2.6.4 command to build the gobblin according to the README file,but build failed.  the build info :
FAILURE: Build failed with an exception.
- Where:
  Build file '/home/chris/gobblin-gobblin_0.7.0/build.gradle' line: 101
- What went wrong:
  A problem occurred evaluating root project 'gobblin-gobblin_0.7.0'.
  
  > Process 'command 'git'' finished with non-zero exit value 128
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by chavdar** [comment]
Is this command run on a copy cloned from git?

**Comment by Tracy6465** [comment]
@chavdar 
I downloaded the source code from the Latest release list. and tar the tar. gz file to my local file system.

**Comment by chavdar** [comment]
Try running

./gradlew clean build -PhadoopVersion=2.6.4 -Pversion=0.7.0

**Comment by Tracy6465** [comment]
@chavdar  
  I  runned the command,  build  failed. 

FAILURE: Build completed with 3 failures.

1: Task failed with an exception.
-----------
* What went wrong:
java.io.IOException: 权限不够
> 权限不够


the Chinese  words"权限不够" means Insufficient privileges.

should I use the root accout  run it ?

**Comment by chavdar** [comment]
You need right permissions to the project's directory. Is the directory
owned by root?

**Comment by Tracy6465** [comment]
@chavdar 
  no. in my /home/chirs .
 later, I cloned the  soure code  by git,and compiled it,but now , I run the command ./gobblin-mapreduce.sh  --workdir /home/gobblin-work-dir --conf ../jobconf/job.pull, there is an exception：
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/local/gobblin-dist/lib/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" gobblin.runtime.JobException: Job job_GobblinKafkaQuickStart_1472614259932 failed
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:363)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.launchJob(CliMRJobLauncher.java:84)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:61)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
