### ISSUE TITLE
gobblin.source.extractor.filebased.FileBasedSource  191 - Not able to fetch the filename/file modified time to Failed to get modified timestamp due to error Cannot open a channel to SFTP server will not pull any files

### ISSUE THREAD

**Issue by abraham0477** [linkedin/gobblin#1267]
Hi, 
I have gobblin installed on a standalone linux server and my ingestion job is basically connecting to a remote server using sftp extracts the files from the remote server, convert them to avro and publish them out to S3. 

I already tested the job and the test went successful, my issue here is I am seeing an error thrown as "gobblin.source.extractor.filebased.FileBasedSource  191 - Not able to fetch the filename/file modified time to Failed to get modified timestamp for file at path filename due to error Cannot open a channel to SFTP server will not pull any files"

I want to mention out here that the error is throwing after processed a certain amount of files, let's say if I have 100 files, the ingestion processed stops after processed and ingested 10 files.

Here is the log file output, and I appreciate any feedback here to fix this issue?

016-09-12 18:26:33 UTC INFO  [TaskExecutor-0] gobblin.source.extractor.extract.sftp.SftpFsHelper$SftpGetMonitor  317 - Transfer finished 1 src: /home/clduser/poller/archive/mibs-3dfd4c3a-d64e-42d0-99fb-0608ff648579-1473303473.csv.gz dest: ?? in 0 at 0.00
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.publisher.TaskPublisher  43 - All components finished successfully, checking quality tests
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.publisher.TaskPublisher  45 - All required test passed for this task passed.
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.publisher.TaskPublisher  47 - Cleanup for task publisher executed successfully.
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.runtime.Fork  261 - Committing data for fork 0 of task task_aphealth_ingestion_98.119.181.163_1473704782375_8
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.writer.FsDataWriter  172 - Moving data from /home/clduser/gobblin-dist/gobblin-working/98.119.181.163/task-staging/aphealth/partitionedPath=2016/09/12/part.task_aphealth_ingestion_98.119.181.163_1473704782375_8_0.avro to /home/clduser/gobblin-dist/gobblin-working/98.119.181.163/task-output/aphealth/partitionedPath=2016/09/12/part.task_aphealth_ingestion_98.119.181.163_1473704782375_8_0.avro
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.util.ExecutorsUtils  125 - Attempting to shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@bf7c83b[Shutting down, pool size = 1, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.util.ExecutorsUtils  144 - Successfully shutdown ExecutorService: java.util.concurrent.ScheduledThreadPoolExecutor@bf7c83b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
2016-09-12 18:26:33 UTC INFO  [TaskExecutor-1] gobblin.source.extractor.extract.sftp.SftpFsHelper$JSchLogger  359 - Disconnecting from 98.119.181.163 port 22

------------
Error started throwing here:

-cd8ff2c73ce4-1473616674.csv.gz due to error Cannot open a channel to SFTP server will not pull any files
gobblin.source.extractor.filebased.FileBasedHelperException: Failed to get modified timestamp for file at path /home/clduser/poller/archive/mibs-a1a20f6e-1c85-4ce1-9ecc-cd8ff2c73ce4-1473616674.csv.gz due to error Cannot open a channel to SFTP server
	at gobblin.source.extractor.extract.sftp.SftpFsHelper.getFileMTime(SftpFsHelper.java:485)
	at gobblin.source.extractor.filebased.FileBasedSource.getcurrentFsSnapshot(FileBasedSource.java:187)
	at gobblin.source.extractor.filebased.FileBasedSource.getWorkunits(FileBasedSource.java:106)
	at gobblin.runtime.SourceDecorator.getWorkunits(SourceDecorator.java:54)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:242)
	at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:353)
	at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:311)
	at gobblin.scheduler.JobScheduler$NonScheduledJobRunner.run(JobScheduler.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: 0: Cannot open a channel to SFTP server
	at gobblin.source.extractor.extract.sftp.SftpFsHelper.getSftpChannel(SftpFsHelper.java:98)
	at gobblin.source.extractor.extract.sftp.SftpFsHelper.getFileMTime(SftpFsHelper.java:481)
	... 10 more
Caused by: com.jcraft.jsch.JSchException: channel is not opened.
	at com.jcraft.jsch.Channel.sendChannelOpen(Channel.java:768)
	at com.jcraft.jsch.Channel.connect(Channel.java:151)
	at com.jcraft.jsch.Channel.connect(Channel.java:145)
	at gobblin.source.extractor.extract.sftp.SftpFsHelper.getSftpChannel(SftpFsHelper.java:95)

Let me know if you want me to send the job config details, again the job is working fine when I have a small amount of files and its failed after reached a certain amount.

**Comment by sahilTakiar** [comment]
The job config would be useful.

Does it always fail when pulling this file `/home/clduser/poller/archive/mibs-a1a20f6e-1c85-4ce1-9ecc-cd8ff2c73ce4-1473616674.csv.gz` or is it a different file each time?

**Comment by sidarthakarna** [comment]
@sahilTakiar When we try to get a huge number of files using sftp, we are only able to pull only 10 files at once. After which it is throwing an exception. It doesn't depend on the nature of the files. It is due to the issue in SftpFsHelper.java. The sftp channel opened in getFileSize doesn't seem to be closed and thus sshd is allowing to open only 10 channels at once.
We fixed the issue with the following change:

```
  @Override
  public long getFileSize(String filePath) throws FileBasedHelperException {
    try {
      ChannelSftp channelSftp = getSftpChannel();
      long fileSize = channelSftp.lstat(filePath).getSize();
      channelSftp.disconnect();
      return fileSize;
    } catch (SftpException e) {
      throw new FileBasedHelperException(
          String.format("Failed to get size for file at path %s due to error %s", filePath, e.getMessage()), e);
    }
  }
```

HTH

**Comment by ibuenros** [comment]
Could you open a pull request with this fix?
Thanks!

**Comment by abraham0477** [comment]
Thanks for the update! the given code resolved this issue.
