### ISSUE TITLE
Failed to create ORC files

### ISSUE THREAD

**Issue by jeffwang66** [linkedin/gobblin#1272]
Hi, 

I am using Gobblin 0.8 to run a MR job which creates ORC files. However, I got this exception in my MR job:

org.apache.hadoop.fs.viewfs.NotInMountpointException: getDefaultReplication on empty path is invalid
	at org.apache.hadoop.fs.viewfs.ViewFileSystem.getDefaultReplication(ViewFileSystem.java:593)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.getStream(WriterImpl.java:1967)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.flushStripe(WriterImpl.java:1984)
	at org.apache.hadoop.hive.ql.io.orc.WriterImpl.close(WriterImpl.java:2289)
	at org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat$OrcRecordWriter.close(OrcOutputFormat.java:106)

The hadoop version I am running is hadoop-2.6.0-cdh5.7.3

Can someone help me about it? Thanks

**Comment by sahilTakiar** [comment]
Could be related to https://issues.apache.org/jira/browse/HIVE-3645

Are you using a federated Namenode? Since the root exception is in the Hive code-base, you may want to try emailing the hive-users list, they may know better.
