### ISSUE TITLE
Hit ClassNotFound issue that SimpleJsonSource class is not found when running SimpleJson example in MapReduce mode

### ISSUE THREAD

**Issue by bit1129** [linkedin/gobblin#1321]
When I run the SimpleJson example with MapReduce mode, in the yarn log, i see that SimepleJsonSource  class is not found on the classpath.

java.lang.RuntimeException: java.lang.ClassNotFoundException: gobblin.example.simplejson.SimpleJsonSource
  at gobblin.runtime.TaskContext.getSource(TaskContext.java:94)
  at gobblin.runtime.TaskContext.getExtractor(TaskContext.java:119)

I looked at the gobblin-mapreduce.sh, the gobblin-example.0.8.0.jar should be added on the classpath

**Comment by bit1129** [comment]
I fixed this problem by manually add the example.jar on the classpath.
