### ISSUE TITLE
job_conf.tar.gz does not exist

### ISSUE THREAD

**Issue by bit6017** [linkedin/gobblin#1343]
I am able to run the Gobblin on YARN,which acts as ever running YARN application. My Hadoop cluster is running on a single machine, that is, the hadoop/yarn is running is standalone mode.
When the gobblin on yarn is running, I notice that there are 3 containers are running. On one of the them, there is an exception in the log:

2016-10-25 16:07:29 CST INFO  [JobConfigurationManager STARTING] gobblin.cluster.JobConfigurationManager  - Loading job configurations from /home/hadoop/data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1477361779465_0009/container_1477361779465_0009_01_000001/job_conf.tar.gz
2016-10-25 16:07:29 CST INFO  [YarnService STARTING] gobblin.yarn.YarnService  - Starting the YarnService
2016-10-25 16:07:29 CST INFO  [GobblinHelixJobScheduler STARTING] gobblin.scheduler.JobScheduler  - Starting the job scheduler
2016-10-25 16:07:29 CST INFO  [YarnService STARTING] org.apache.hadoop.yarn.client.RMProxy  - Connecting to ResourceManager at /0.0.0.0:8030
2016-10-25 16:07:30 CST INFO  [SchedulerService STARTING] org.quartz.impl.StdSchedulerFactory  - Using default implementation for ThreadExecutor
2016-10-25 16:07:30 CST INFO  [SchedulerService STARTING] org.quartz.simpl.SimpleThreadPool  - Job execution threads will use class loader of thread: SchedulerService STARTING
2016-10-25 16:07:30 CST ERROR [JobConfigurationManager STARTING] gobblin.util.PullFileLoader  - Could not load properties at path: /home/hadoop/data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1477361779465_0009/container_1477361779465_0009_01_000001/job_conf.tar.gz
java.io.FileNotFoundException: File /home/hadoop/data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1477361779465_0009/container_1477361779465_0009_01_000001/job_conf.tar.gz does not exist.
    at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:647)
    at org.apache.hadoop.hdfs.DistributedFileSystem.access$600(DistributedFileSystem.java:101)
    at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:705)
    at org.apache.hadoop.hdfs.DistributedFileSystem$14.doCall(DistributedFileSystem.java:701)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:701)
    at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1483)
    at org.apache.hadoop.fs.FileSystem.listStatus(FileSystem.java:1523)
    at gobblin.util.PullFileLoader.findAndLoadGlobalConfigInDirectory(PullFileLoader.java:223)
    at gobblin.util.PullFileLoader.loadPullFilesRecursivelyHelper(PullFileLoader.java:159)
    at gobblin.util.PullFileLoader.loadPullFilesRecursively(PullFileLoader.java:148)
    at gobblin.util.SchedulerUtils.loadGenericJobConfigs(SchedulerUtils.java:65)
    at gobblin.cluster.JobConfigurationManager.startUp(JobConfigurationManager.java:80)
    at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
    at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
    at java.lang.Thread.run(Thread.java:745)
2016-10-25 16:07:30 CST INFO  [JobConfigurationManager STARTING] gobblin.cluster.JobConfigurationManager  - Loaded 0 job configuration(s)

I checked my local file system, and find that /home/hadoop/data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1477361779465_0009/container_1477361779465_0009_01_000001/job_conf.tar.gz actually exists, and job_conf.tar.gz is a directory,there are job_conf/simplejson.pull under it.

I am not sure what's going wrong there,

**Comment by bit1129** [comment]
Can someone on the team please take a look at this problem? It blocks my work now.Thanks a lot!!

**Comment by bit1129** [comment]
Following are the application.conf and reference.conf

**application.conf**

`
gobblin.yarn.app.name=GobblinYarn
gobblin.yarn.app.master.memory.mbs=256
gobblin.yarn.initial.containers=2
gobblin.yarn.container.memory.mbs=512
gobblin.yarn.conf.dir="/home/hadoop/gobblin-distribution-0.8.0/gobblin-dist/conf/yarn"
gobblin.yarn.lib.jars.dir="/home/hadoop/gobblin-distribution-0.8.0/gobblin-dist/lib"
gobblin.yarn.app.master.files.local=${gobblin.yarn.conf.dir}"/log4j-yarn.properties,"${gobblin.yarn.conf.dir}"/application.conf,"${gobblin.yarn.conf.dir}"/reference.conf"
gobblin.yarn.container.files.local=${gobblin.yarn.app.master.files.local}
gobblin.yarn.logs.sink.root.dir=/tmp/gobblin_yarn_logs_sink


gobblin.cluster.helix.cluster.name=GobblinYarn
gobblin.cluster.job.conf.path="/home/hadoop/gobblin-distribution-0.8.0/gobblin-dist/bin/json_sample/job_conf"
gobblin.yarn.job.conf.path="/home/hadoop/gobblin-distribution-0.8.0/gobblin-dist/bin/json_sample/job_conf"

jobconf.fullyQualifiedPath="/home/hadoop/gobblin-distribution-0.8.0/gobblin-dist/bin/json_sample/job_conf"

gobblin.yarn.work.dir=/user/hadoop/gobblin_yarn_work


writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}


writer.destination.type=HDFS
writer.output.format=AVRO
writer.staging.dir=${gobblin.yarn.work.dir}/task-staging
writer.output.dir=${gobblin.yarn.work.dir}/task-output


data.publisher.type=gobblin.publisher.BaseDataPublisher
data.publisher.final.dir=${gobblin.yarn.work.dir}/job-output
data.publisher.replace.final.dir=false


state.store.dir=${gobblin.yarn.work.dir}/state-store


qualitychecker.row.err.file=${gobblin.yarn.work.dir}/err


job.lock.enabled=false


job.lock.dir=${gobblin.yarn.work.dir}/locks


metrics.log.dir=${gobblin.yarn.work.dir}/metrics


task.status.reportintervalinms=1000


metrics.enabled=true

admin.server.enabled=false

`

**reference.conf**

gobblin.yarn.app.queue=default
gobblin.yarn.app.name=GobblinYarn
gobblin.yarn.app.master.memory.mbs=512
gobblin.yarn.app.master.cores=1
gobblin.yarn.app.report.interval.minutes=5
gobblin.yarn.max.get.app.report.failures=4
gobblin.yarn.email.notification.on.shutdown=false
gobblin.yarn.initial.containers=1
gobblin.yarn.container.memory.mbs=512
gobblin.yarn.container.cores=1
gobblin.yarn.container.affinity.enabled=true
gobblin.yarn.helix.instance.max.retries=2
gobblin.yarn.keytab.login.interval.minutes=1440
gobblin.yarn.token.renew.interval.minutes=720
gobblin.yarn.work.dir=/home/hadoop/gobblin_yarn_work
gobblin.cluster.helix.cluster.name=GobblinYarn
gobblin.cluster.zk.connection.string="localhost:2181"
fs.uri="hdfs://localhost:9000"
job.execinfo.server.enabled=false

**Comment by bit1129** [comment]
@autumnust @abti @sahilTakiar

**Comment by bit1129** [comment]
From the exception, the exception is thrown from https://github.com/linkedin/gobblin/blob/gobblin_0.8.0/gobblin-utility/src/main/java/gobblin/util/PullFileLoader.java, line 82 

 **FileStatus[] statuses = this.fs.listStatus(path);**

But I can't figure out what the problem is there since the path does exist.


@ibuenros @autumnust

**Comment by bit1129** [comment]
One more thing, the following log should tell  that 
**/home/hadoop/data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1477361779465_0009/container_1477361779465_0009_01_000001/job_conf.tar.gz** exists


2016-10-25 16:07:29 CST INFO [JobConfigurationManager STARTING] gobblin.cluster.JobConfigurationManager - Loading job configurations from /home/hadoop/data/tmp/nm-local-dir/usercache/hadoop/appcache/application_1477361779465_0009/container_1477361779465_0009_01_000001/job_conf.tar.gz

**Comment by ibuenros** [comment]
Hello,
Gobblin on YARN is considered experimental at the moment, and we
unfortunately don't have resources to debug this issue (and we don't know
outright what the issue is). Is there any reason you can't run this in MR
mode?
Issac

**Comment by abti** [comment]
Hi @bit1129 

Yes, it seems the path that you mentioned does exists because it passed through the existence check (as per code) before running into an exception later. 
It seems @jsavolainen also ran into the same issue, which was introduced during recent changes around how we load configs: https://github.com/linkedin/gobblin/pull/1259 

@jsavolainen was kind to contribute a fix back. So, can you please try to build from source and use that rather than the current release distribution that you are using? It should hopefully help.
