### ISSUE TITLE
Gobblin google bucket support

### ISSUE THREAD

**Issue by Abhisrajput** [linkedin/gobblin#1370]
We are witting messages from kafka to aws s3 buckets. Now we are planning to migrate to google bucket. Do we have similar support for google bucket.

**Comment by chavdar** [comment]
Hi,

By installing the Google Hadoop connector (
https://cloud.google.com/hadoop/google-cloud-storage-connector), you should
be able to access Google buckets as any other Hadoop file system.

**Comment by pankajPD** [comment]
Gobblin is not able to recognize 'gs' filesystem. Is there any other option?

**Comment by chavdar** [comment]
Can you be a bit more specific? What do you mean that by "Gobblin is not
able to recognize 'gs' filesystem"? What is the error that you get?

**Comment by pankajPD** [comment]
Hi Chavdar,

I am getting following error:
Caused by: java.io.IOException: No FileSystem for scheme: gs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2304)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2311)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:90)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2350)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:233

**Comment by chavdar** [comment]
Can you please provide the full stack and some logs that show when the
error happens? Are you running in M/R mode? If yes, is the error happening
in the driver or in the mappers?

**Comment by Abhisrajput** [comment]
Below is our pull file
```
job.name=UserContent
job.group=Kafka2s3
job.description=Kafka To S3

job.schedule=0 0/10 * * * ?

source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=kafkaToS3

topic.whitelist=GS_SA_IN_TR_UC
bootstrap.with.offset=latest

kafka.brokers=instance1.spark.com:9092,instance2.spark.com:9092,instance3.spark.com:9092

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
simple.writer.delimiter=\n
writer.destination.type=HDFS
writer.output.format=JSON

data.publisher.fs.uri=gs://ngdp_sa
state.store.fs.uri=gs://ngdp_sa

writer.output.schema={""}
mr.job.max.mappers=10

job.lock.enabled=false

data.publisher.type=gobblin.publisher.BaseDataPublisher
```
Error:
```
2017-01-03 13:54:07 UTC INFO  [main] org.quartz.impl.StdSchedulerFactory  1172 - Using default implementation for ThreadExecutor
2017-01-03 13:54:07 UTC INFO  [main] org.quartz.core.SchedulerSignalerImpl  61 - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2017-01-03 13:54:07 UTC INFO  [main] org.quartz.core.QuartzScheduler  240 - Quartz Scheduler v.2.2.3 created.
2017-01-03 13:54:07 UTC INFO  [main] org.quartz.simpl.RAMJobStore  155 - RAMJobStore initialized.
2017-01-03 13:54:07 UTC INFO  [main] org.quartz.core.QuartzScheduler  305 - Scheduler meta-data: Quartz Scheduler (v2.2.3) 'LocalJobScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 3 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2017-01-03 13:54:07 UTC INFO  [main] org.quartz.impl.StdSchedulerFactory  1327 - Quartz scheduler 'LocalJobScheduler' initialized from specified file: '/home/hadoop/gobblin-dist/conf/quartz.properties'
2017-01-03 13:54:07 UTC INFO  [main] org.quartz.impl.StdSchedulerFactory  1331 - Quartz scheduler version: 2.2.3
2017-01-03 13:54:07 UTC INFO  [main] gobblin.runtime.app.ServiceBasedAppLauncher  141 - Starting the Gobblin application and all its associated Services
2017-01-03 13:54:07 UTC INFO  [JobScheduler STARTING] gobblin.scheduler.JobScheduler  146 - Starting the job scheduler
2017-01-03 13:54:07 UTC INFO  [JobScheduler STARTING] org.quartz.core.QuartzScheduler  575 - Scheduler LocalJobScheduler_$_NON_CLUSTERED started.
2017-01-03 13:54:07 UTC INFO  [JobScheduler STARTING] gobblin.scheduler.JobScheduler  365 - Scheduling locally configured jobs
2017-01-03 13:54:07 UTC INFO  [JobScheduler STARTING] gobblin.scheduler.JobScheduler  378 - Loaded 1 job configuration
2017-01-03 14:00:00 UTC WARN  [LocalJobScheduler_Worker-1] org.apache.hadoop.util.NativeCodeLoader  62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2017-01-03 14:00:01 UTC INFO  [LocalJobScheduler_Worker-1] org.quartz.core.JobRunShell  207 - Job Kafka2s3.UserContent threw a JobExecutionException:
org.quartz.JobExecutionException: gobblin.runtime.JobException: Failed to run job UserContent [See nested exception: gobblin.runtime.JobException: Failed to run job UserContent]
        at gobblin.scheduler.JobScheduler$GobblinJob.execute(JobScheduler.java:514)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: gobblin.runtime.JobException: Failed to run job UserContent
        at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:294)
        at gobblin.scheduler.JobScheduler$GobblinJob.execute(JobScheduler.java:512)
        ... 2 more
Caused by: java.io.IOException: No FileSystem for scheme: gs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2304)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2311)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:90)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2350)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2332)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:369)
        at gobblin.runtime.JobContext.<init>(JobContext.java:124)
        at gobblin.runtime.AbstractJobLauncher.<init>(AbstractJobLauncher.java:131)
        at gobblin.runtime.local.LocalJobLauncher.<init>(LocalJobLauncher.java:59)
        at gobblin.runtime.JobLauncherFactory.newJobLauncher(JobLauncherFactory.java:63)
        at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:292)
        ... 3 more

```

**Comment by chavdar** [comment]
Thank you.

It looks like the error is during start up in the instance driver. This
most likely means that the bucket connector was not installed or properly
configured. Have you followed the instructions at
https://cloud.google.com/hadoop/google-cloud-storage-connector#manualinstallation
for installing the connector?

**Comment by Abhisrajput** [comment]
Thanks Chavdar,

bucket connector is installed properly I'm able to list down the files:

```
hadoop@instance-3:~/gobblin-dist/logs$ hadoop fs -ls gs://ngdp_sa
17/01/09 12:18:04 INFO gcs.GoogleHadoopFileSystemBase: GHFS version: 1.6.0-hadoop2
Found 3 items
drwx------   - hadoop hadoop          0 2017-01-06 08:51 gs://ngdp_sa/archive
drwx------   - hadoop hadoop          0 2017-01-06 10:29 gs://ngdp_sa/user
drwx------   - hadoop hadoop          0 2017-01-06 13:25 gs://ngdp_sa/work
```
but not sure I'm getting the above error.

**Comment by abti** [comment]
It seems you do not have the connector jars on classpath that are
referenced here:
https://cloud.google.com/hadoop/google-cloud-storage-connector#getting

As per logs, I am assuming you are using Gobblin standalone, so the easiest
way to get those jars on classpath is to copy them to lib directory within
the Gobblin distribution.

You are able to do a hadoop fs -ls because that is possibly using your
HADOOP_HOME or similar classpath which is not referenced by Gobblin
standalone.

Hope that helps.

Regards
Abhishek

**Comment by Abhisrajput** [comment]
Thanks Abhishek for your response.

I already added the connector jar path in the hadoop-env.sh file
`export HADOOP_CLASSPATH=$HADOOP_CLASSPATH:/home/hadoop/gcs-connector-latest-hadoop2.jar`

Even I'm able to access google bucket files in my Spark job the only issue I'm facing here.

**Comment by Abhisrajput** [comment]
Thanks everyone.
Now able to write the files in the google bucket.
Issues:
1.) Ready only role provided in the google bucket.
2.) Added fs.gs.project.id = xxxxxxxxxx in the pull file.
