### ISSUE TITLE
error in gobblin on yarn

### ISSUE THREAD

**Issue by Riordon** [linkedin/gobblin#1378]
when I run the example of gobblin on yarn in lastest version , I get a error :
`WARN [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
WARN [ZKHelixAdmin] Root directory exists.Cleaning the root directory:/GobblinYarn
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'admin'
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:124)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:147)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164)
	at com.typesafe.config.impl.SimpleConfig.getBoolean(SimpleConfig.java:174)
	at gobblin.yarn.GobblinYarnAppLauncher.launch(GobblinYarnAppLauncher.java:285)
	at gobblin.yarn.GobblinYarnAppLauncher.main(GobblinYarnAppLauncher.java:794)
ERROR [GobblinYarnAppLauncher] Failed to shutdown the GobblinYarnAppLauncher
java.io.IOException: Filesystem closed
	at org.apache.hadoop.hdfs.DFSClient.checkOpen(DFSClient.java:857)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:2118)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:1215)
	at org.apache.hadoop.hdfs.DistributedFileSystem$19.doCall(DistributedFileSystem.java:1211)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1211)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1412)
	at gobblin.yarn.GobblinYarnAppLauncher.cleanUpAppWorkDirectory(GobblinYarnAppLauncher.java:729)
	at gobblin.yarn.GobblinYarnAppLauncher.stop(GobblinYarnAppLauncher.java:324)
	at gobblin.yarn.GobblinYarnAppLauncher$2.run(GobblinYarnAppLauncher.java:781)
`
I Lookup Code , find 
`String clusterName = this.config.getString(GobblinClusterConfigurationKeys.HELIX_CLUSTER_NAME_KEY);`
but GobblinClusterConfigurationKeys don't contain HELIX_CLUSTER_NAME_KEY

**Comment by sharanreddy2001** [comment]
I'm also facing the similar issue. Could you let us know what changes made this error go away ?
