### ISSUE TITLE
[Help Needed] kafka Json to hdfs Avro

### ISSUE THREAD

**Issue by manugarri** [linkedin/gobblin#1395]
First of all, thanks to everyone working on this project, looks very good.
Second,  I apologize if this is included in the docs/examples. Cant seem to find it.

My issue is, I have a kafka topic already running with json encoded data.

I would like to send it to HDFS as Avro formatted data. The data in kafka looks like:
```
{"field1": "value", "field2":"value2"}
{"field1": "value3", "field2":"value4"}
```
That is, simple json messages (1 per message).

 However, I cant seem to find the right job configuration to make it work.

## Things I tried:

```
source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource

writer.builder.class=gobblin.writer.AvroHdfsDataWriter
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=AVRO
```

This gives me the error:

```
ava.lang.RuntimeException: java.lang.InstantiationException: gobblin.writer.AvroHdfsDataWriter
	at gobblin.runtime.TaskContext.getDataWriterBuilder(TaskContext.java:296)
	at gobblin.runtime.Fork.buildWriter(Fork.java:370)
	at gobblin.runtime.Fork.buildWriterIfNotPresent(Fork.java:382)
	at gobblin.runtime.Fork.processRecords(Fork.java:399)
	at gobblin.runtime.Fork.run(Fork.java:170)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
...
```
Which, even though is not very explicit, seems to be an error on avro trying to write as avro a json encoded string.

```
source.class=gobblin.source.extractor.extract.kafka.KafkaDeserializerSource
kafka.deserializer.type=STRING

converter.classes=gobblin.converter.json.JsonStringToJsonIntermediateConverter,gobblin.converter.avro.JsonIntermediateToAvroConverter

writer.builder.class=gobblin.writer.AvroHdfsDataWriter
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=AVRO
```

This gives me the error: 
```
java.lang.IllegalStateException: This is not a JSON Array.
	at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106)
	at gobblin.converter.json.JsonStringToJsonIntermediateConverter.convertSchema(JsonStringToJsonIntermediateConverter.java:45)
	at gobblin.converter.json.JsonStringToJsonIntermediateConverter.convertSchema(JsonStringToJsonIntermediateConverter.java:26)
	at gobblin.instrumented.converter.InstrumentedConverterDecorator.convertSchema(InstrumentedConverterDecorator.java:72)
	at gobblin.runtime.MultiConverter.convertSchema(MultiConverter.java:68)
	at gobblin.runtime.Task.run(Task.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
...
```

Which looking at [JsonStringToJsonIntermediateConverter](https://github.com/linkedin/gobblin/blob/master/gobblin-core/src/main/java/gobblin/converter/json/JsonStringToJsonIntermediateConverter.java#L39), might be failling because of **JsonStringToJsonIntermediateConverter** not receiving an schema?. 

```
source.class=gobblin.source.extractor.extract.kafka.KafkaDeserializerSource
kafka.deserializer.type=GSON #this should return a jsonObject
converter.classes=gobblin.converter.avro.JsonIntermediateToAvroConverter
#converter.avro.nullify.fields.enabled=True

writer.builder.class=gobblin.writer.AvroHdfsDataWriter
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=AVRO
```

This gives me the error:
```
java.lang.ClassCastException: java.lang.String cannot be cast to com.google.gson.JsonArray
	at gobblin.converter.avro.JsonIntermediateToAvroConverter.convertSchema(JsonIntermediateToAvroConverter.java:52)
	at gobblin.instrumented.converter.InstrumentedConverterDecorator.convertSchema(InstrumentedConverterDecorator.java:72)
	at gobblin.runtime.MultiConverter.convertSchema(MultiConverter.java:68)
	at gobblin.runtime.Task.run(Task.java:139)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
```
Even though  KafkaSerializer is supposed to return a JsonObject, it seems the converter is still receiving a JsonIntermediateToAvroConverter.

Thats the point I am at right now. Any help would be more than welcome.

**Comment by jeffwang66** [comment]
I think you need to write your converter class to convert JsonElement to GenericRecord. 
Hope it helps.

**Comment by manugarri** [comment]
Thanks @jeffwang66 , do you know if there is any converter already done that would work?

**Comment by jeffwang66** [comment]
@manugarri I don't think there is one can be directly used. But you can create one based on the existing converter: https://github.com/linkedin/gobblin/blob/master/gobblin-core/src/main/java/gobblin/converter/json/JsonToStringConverter.java

In the method convertRecord(), you just need to return GenericRecord

**Comment by shirshanka** [comment]
@manugarri As @jeffwang66 says, you will need to write a converter. 

One tricky piece will be creating the Avro schema. Do you know ahead of time what the Avro schema for the dataset will be? Is this a single topic or are you pulling multiple topics in the same pipeline?

**Comment by manugarri** [comment]
Thanks for your reply @shirshanka.

Yes, the schema will be predefined, so that is a plus.

I am not a java person myself, do you have any guidelines to how to implement this converter? 

I thought that Javaserializer with GSON option would turn the kafka []byte into google JsonObject, would I then need to implement something that turned that into avro then? 

Do you have by any chance any advice in how to implement this? Im a bit lost here.

**Comment by shirshanka** [comment]
@manugarri : You can use https://github.com/linkedin/gobblin/blob/master/gobblin-core/src/main/java/gobblin/converter/avro/JsonIntermediateToAvroConverter.java as an example to see how to turn Json into Avro.

**Comment by abti** [comment]
Please reopen if still an open question?

**Comment by manugarri** [comment]
It is still an open question, nobody has provided a helpful answer :(
