### ISSUE TITLE
Unknown protocol exception on start of Kafka-HDFS ingestion

### ISSUE THREAD

**Issue by wosiu** [linkedin/gobblin#1464]
Not sure is it a bug or I'm doing something wrong, I've tried to follow turtorial. When I'm starting ingestion I get:

```
Exception in thread "main" org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.ipc.RpcNoSuchProtocolException): Unknown protocol: org.apache.hadoop.hdfs.protocol.ClientProtocol
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.getProtocolImpl(ProtobufRpcEngine.java:559)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine.java:598)
	at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1060)
	at org.apache.hadoop.ipc.Server$Handlerrun(Server.java:2044)
	at org.apache.hadoop.ipc.Server$Handlerrun(Server.java:2040)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2038)

	at org.apache.hadoop.ipc.Client.call(Client.java:1468)
	at org.apache.hadoop.ipc.Client.call(Client.java:1399)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
	at com.sun.proxy.$Proxy10.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:752)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy11.getFileInfo(Unknown Source)
	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1982)
	at org.apache.hadoop.hdfs.DistributedFileSystemdoCall(DistributedFileSystem.java:1128)
	at org.apache.hadoop.hdfs.DistributedFileSystemdoCall(DistributedFileSystem.java:1124)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1124)
	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1400)
	at gobblin.runtime.FsDatasetStateStore.getLatestDatasetStatesByUrns(FsDatasetStateStore.java:156)
	at gobblin.runtime.JobContext.<init>(JobContext.java:136)
	at gobblin.runtime.AbstractJobLauncher.<init>(AbstractJobLauncher.java:131)
	at gobblin.runtime.mapreduce.MRJobLauncher.<init>(MRJobLauncher.java:127)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.<init>(CliMRJobLauncher.java:54)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```

The way I build:
```
./gradlew -Pversion=gobblin_0.8.0 -PhadoopVersion=2.6.0-cdh5.4.3 -q clean assemble
```
(I tried top of the master as well and PhadoopVersion=2.6.0 too)

I'm running like this:
```
export GOBBLIN_JOB_CONFIG_DIR=/home/michalw/gobblin-job-config
export JAVA_HOME=/opt/sun-java-jdk/8u60  # must containt /bin/java exec
export GOBBLIN_WORK_DIR=/home/michalw/gobblin-work
#export HADOOP_BIN_DIR=/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hadoop/bin # must contain hadoop exec
export HADOOP_BIN_DIR=/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/bin
export HADOOP_HOME=/opt/cloudera/parcels/CDH-5.4.3-1.cdh5.4.3.p0.6/lib/hadoop-0.20-mapreduce

./gobblin-dist/bin/gobblin-mapreduce.sh --conf gobblin-job-config/test-job.properties
```

my config in gobblin-job-config/test-job.properties: 
```
job.name=GobblinKafkaQuickStart
job.group=GobblinKafka
job.description=Gobblin quick start job for Kafka
job.lock.enabled=false

kafka.brokers=mach2019:9092,mach2029:9092,mach2030:9092,mach2031:9092,mach2032:9092,mach2110:9092,mach2113:9092,mach2120:9092,mach311:9092,mach328:9092,mach340:9092,mach425:9092,mach430:9092,mach533:9092,mach534:9092,mach536:9092,mach606:9092,mach614:9092,mach637:9092,mach638:9092,mach639:9092,mach640:9092,mach715:9092,mach720:9092,mach721:9092,mach811:9092

topic.whitelist=test.topicname

source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=txt

data.publisher.type=gobblin.publisher.BaseDataPublisher

mr.job.max.mappers=1

metrics.reporting.file.enabled=true
metrics.log.dir=/home/michalw/gobblin-kafka/metrics
metrics.reporting.file.suffix=txt

bootstrap.with.offset=earliest

fs.uri=hdfs://machine2006:50020
writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}

mr.job.root.dir=/home/michalw/gobblin-kafka/working
state.store.dir=/home/michalw/gobblin-kafka/state-store
task.data.root.dir=/home/michalw/jobs/kafkaetl/gobblin/gobblin-kafka/task-data
data.publisher.final.dir=/home/michalw/gobblintest/job-output
```

**Comment by ydai1124** [comment]
Hi,

Can you check if your fs.uri is correct by executing "hadoop fs -ls
hdfs://machine2006:50020"?

**Comment by wosiu** [comment]
Thank you for quick response. My bad - I put wrong port in the config. Thank you!
Is there any better place to ask questions regarding starting up and documentation? I have some more doubts, but I guess my problems are not really connected with bugs.

**Comment by chavdar** [comment]
Hi,

You can use the gobblin-users@googlegroups.com group.
