### ISSUE TITLE
Parallel publish to S3

### ISSUE THREAD

**Issue by apurva-sharma** [linkedin/gobblin#1491]
I need to publish data to s3 at the end of a gobblin run.
This seems to work but is rather slow. I notice that the files are first downloaded from hdfs to a local directory and then copied to s3, making the namenode (master) a network bottleneck.
Is it possible for the mappers to directly publish their data to s3?
Or at least use a distcp like approach for moving data from hdfs to S3?
I took a look at existing documentation for Gobblin-Distcp but could not find any case studies/examples for this.
Any thoughts on how to speed up this s3 copy?

**Comment by shirshanka** [comment]
@apurva-sharma Can you share relevant sections of your pull/job file so we can understand exactly how you are setting up the pipeline?

**Comment by apurva-sharma** [comment]
And I see this in the gobblin logs:

> 2017-01-01 21:15:24 UTC INFO  [ParallelRunner] com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient  614 - Unable to execute HTTP request: Connection reset
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at sun.security.ssl.OutputRecord.writeBuffer(OutputRecord.java:377)
	at sun.security.ssl.OutputRecord.write(OutputRecord.java:363)
	at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:837)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:808)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:181)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:115)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.entity.InputStreamEntity.writeTo(InputStreamEntity.java:142)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.RepeatableInputStreamRequestEntity.writeTo(RepeatableInputStreamRequestEntity.java:153)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.entity.HttpEntityWrapper.writeTo(HttpEntityWrapper.java:89)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.EntityEnclosingRequestWrapper$EntityWrapper.writeTo(EntityEnclosingRequestWrapper.java:108)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:117)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:265)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.conn.ManagedClientConnectionImpl.sendRequestEntity(ManagedClientConnectionImpl.java:203)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:236)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.protocol.SdkHttpRequestExecutor.doSendRequest(SdkHttpRequestExecutor.java:63)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:121)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at com.amazon.ws.emr.hadoop.fs.shaded.org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:837)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
	at com.amazon.ws.emr.hadoop.fs.shaded.com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1405)
	at com.amazon.ws.emr.hadoop.fs.s3n.Jets3tNativeFileSystemStore.storeFile(Jets3tNativeFileSystemStore.java:165)
	at sun.reflect.GeneratedMethodAccessor47.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy23.storeFile(Unknown Source)
	at com.amazon.ws.emr.hadoop.fs.s3n.S3NativeFileSystem$NativeS3FsOutputStream.close(S3NativeFileSystem.java:376)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:106)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:61)
	at org.apache.hadoop.io.IOUtils.copyBytes(IOUtils.java:119)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:366)
	at org.apache.hadoop.fs.FileUtil.copy(FileUtil.java:338)
	at gobblin.util.HadoopUtils.copyPath(HadoopUtils.java:290)
	at gobblin.util.HadoopUtils.movePath(HadoopUtils.java:228)
	at gobblin.util.ParallelRunner$6.call(ParallelRunner.java:306)
	at gobblin.util.ParallelRunner$6.call(ParallelRunner.java:299)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shirshanka** [comment]
Gobblin currently uses the Hadoop filesystem support for interfacing with S3. That has the downside of using  s3 put and download to local as you've discovered.

@sahilTakiar : Do you have any thoughts on this?

**Comment by apurva-sharma** [comment]
@shirshanka thanks for responding, if that is the case, distcp should do better as it splits files and distributes them to mappers - I see a section on gobblin-distcp, but am unsure if it is relevant to my use case. More over, not sure how it would integrate into a workflow like this.
Are there any examples/documentation on this that may help?

**Comment by shirshanka** [comment]
@ibuenros : thoughts on gobblin-distcp ^^ 

@apurva-sharma : sent you an invite for a chat

**Comment by apurva-sharma** [comment]
@shirshanka I do not see an invite, maybe try again?

**Comment by ibuenros** [comment]
@apurva-sharma unfortunately s3a filesystem does not support `concat` operation, which is necessary for splitting files during distcp.
A way of improving performance is to do task-level publishing, which will publish the files in the mapper itself, removing a bottleneck. Note this causes slightly different semantics on failure.

**Comment by sahilTakiar** [comment]
A few thoughts here:

@apurva-sharma 

* The stack trace you have posted below seems to suggest you are using EMR, is that correct? 
* There are a few open-sourced S3 connectors that have been created over the years, see https://aws.amazon.com/premiumsupport/knowledge-center/emr-file-system-s3/
* Looks like you are using the `s3n` connector, you might want to consider using the `s3` connector instead, the AWS docs seem to recommend that
* Turning on multi-part uploads will definitely help, if they are not already enabled. Doing this for the `s3a` connector (not supported by EMR) is pretty easy, but I'm not sure how to do it for `s3` or `s3n`
* There is some work on the `s3a` connector to directly write data from HDFS to S3, without writing to the local filesystem, but a lot of this work is experimental (happy to provide more details)

@shirshanka 

* The JIRA you pointed to above is for the `s3a` connector (not supported by EMR); note that the Hadoop open-source community has more or less deprecated the old connectors (`s3n` and `s3`) and all new development is for the `s3a` connector
* Distcp has its advantages, but we need to be careful when using it; the biggest problem with most S3 connectors is that they emulate the `rename` operation by copying a file and then deleting the original location (S3 does not natively support renaming files)

@ibuenros 

* Yes, that is another option, and some open-source projects that support this (see Hadoop Distcp Commit Algorithm 2 and Spark's DirectOutputCommitter)
* As your said, this does change the failure semantics, and came make more complex, especially when speculative execution and task retries are involved

I believe Gobblin right now will write all data from its map-tasks to HDFS, and then the `Publisher` will be responsible for copying all data from HDFS to S3. I agree this isn't particularly efficient, as the driver process becomes the bottleneck. All data needs to be downloaded to the driver, and then uploaded to S3. An alternative approach, that some other open-source projects take is to write all data from a map task to a staging directory on S3, and then the driver is responsible for copying the data from the staging directory on S3 to the final location on S3. S3-to-S3 copies are done server side, so there is no data flowing through the driver, just an HTTP request to issue the copy.

**Comment by apurva-sharma** [comment]
@ibuenros @sahilTakiar this is extremely helpful, thanks.
Yes, I am using EMR. Which means s3a is not an option(yet). Really hope EMR adds s3a support soon.
So the way I see it, I have 2 options:
1. Hunt around to see if multi-part is possible in s3n.
2. Use external distcp (while it may not be able to split files, it will at least distribute files to multiple machines as opposed to channelling everything through the driver. The flip side is that the failure semantics need to be handled separately.
3. Look into mappers publishing to s3 directly.
Correct?

**Comment by apurva-sharma** [comment]
Read up a little more.
@sahilTakiar looks like multi part for s3n is configurable:
https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/index.html
Lists:

<property>
  <name>fs.s3n.multipart.uploads.enabled</name>
  <value>false</value>
  <description>Setting this property to true enables multiple uploads to
  native S3 filesystem. When uploading a file, it is split into blocks
  if the size is larger than fs.s3n.multipart.uploads.block.size.
  </description>
</property>

I will try playing around with this and see if it helps.

**Comment by sahilTakiar** [comment]
You also may went to use EMRFS instead of `s3n`. The AWS docs recommend EMRFS over `s3n` - http://docs.aws.amazon.com/ElasticMapReduce/latest/DeveloperGuide/emr-plan-file-systems.html

**Comment by apurva-sharma** [comment]
Got it, thanks for the help guys, I will try ^^ and report back any findings here.

**Comment by apurva-sharma** [comment]
Just an update, so yes, the multipart is enabled exactly like I described above and it does seem to take away a lot of the spikes in s3 upload latencies.
I will close this ticket, and hope for s3a on EMR which should be the next adoption for us.
Thanks a lot @shirshanka @ibuenros @sahilTakiar
