### ISSUE TITLE
java.lang.IllegalArgumentException when using extract.limit.enabled

### ISSUE THREAD

**Issue by guilhermef** [linkedin/gobblin#1675]
Hi,
I'm trying to set a time limit on Gobblin when extracting data from kafka,
my job config looks like this:
```
job.name=events
job.group=events
job.description=events
job.lock.enabled=true
job.schedule=0 0 0/1 1/1 * ? *

kafka.brokers=${env:KAFKA_BROKERS}
kafka.workunit.packer.type=BI_LEVEL

source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka
extract.limit.enabled=true
extract.limit.type=time
extract.limit.time.limit=120
extract.limit.time.limit.timeunit=minutes

converter.classes=com.custom.gobblin.GobblinBytesToAvroConverter

writer.partitioner.class=com.custom.gobblin.GobblinDailyPartitioner
writer.partition.pattern=YYYY/MM/dd
writer.partition.columns=timestamp
writer.builder.class=gobblin.writer.AvroDataWriterBuilder
writer.file.path.type=tablename
writer.partition.timezone=UTC
writer.destination.type=HDFS
writer.output.format=AVRO

writer.codec.type=SNAPPY
writer.deflate.level=6
writer.include.partition.in.file.names=false

mr.job.max.mappers=5

topic.whitelist=.*
data.publisher.type=gobblin.publisher.TimePartitionedDataPublisher

metrics.reporting.file.enabled=true
metrics.log.dir=${env:GOBBLIN_WORK_DIR}/metrics
metrics.reporting.file.suffix=txt
```

Looking at the docs, this should work, but I keep getting:

```
2017-03-06 17:15:01 ERROR Task:266 - Task task_events_1488816000695_68 failed
java.lang.IllegalArgumentException
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:77)
	at gobblin.util.limiter.DefaultLimiterFactory.newLimiter(DefaultLimiterFactory.java:74)
	at gobblin.runtime.TaskContext.getExtractor(TaskContext.java:112)
	at gobblin.runtime.Task.run(Task.java:127)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I'm using gobblin 0.8.0.
Thanks.

**Comment by abti** [comment]
jira-assignee:lesun
jira-label:gobblin-os-github

**Comment by ibuenros** [comment]
Hello,

You are using the wrong key. Please use "extract.limit.timeLimit" and
"extract.limit.timeLimitTimeunit" instead. If this is wrong in the docs,
can you please point us to the location so we can fix it?

Thanks,
Issac

**Comment by madiks** [comment]
I found the location in the doc, it's in Case Studies » Kafka-HDFS Ingestion
https://github.com/linkedin/gobblin/blob/master/gobblin-docs/case-studies/Kafka-HDFS-Ingestion.md
https://gobblin.readthedocs.io/en/latest/case-studies/Kafka-HDFS-Ingestion/
