### ISSUE TITLE
MR Job throws Invalid path ' ' Exception

### ISSUE THREAD

**Issue by nirm2009** [linkedin/gobblin#1694]
Trying to run a Gobblin MapReduce job within a Gobblin project cloned and bulit with the command :
**./gradlew clean build -PhadoopVersion=2.7.3 -PjdkVersion=1.8**.
Job run command : **bin/gobblin-mapreduce.sh --conf /user/dasun/gobblin-dist/conf/jobConfig/gobbKafkaHDFSJob4.job**
Thrown Exception :
```
Exception in thread "main" com.typesafe.config.ConfigException$BadPath: path parameter: Invalid path '': path has a leading, trailing, or two adjacent period '.' (use quoted "" empty string if you want an empty element)
	at com.typesafe.config.impl.Parser.parsePathExpression(Parser.java:1110)
	at com.typesafe.config.impl.Parser.parsePath(Parser.java:1135)
	at com.typesafe.config.impl.Path.newPath(Path.java:224)
	at com.typesafe.config.impl.PropertiesParser.fromPathMap(PropertiesParser.java:79)
	at com.typesafe.config.impl.ConfigImpl.fromAnyRef(ConfigImpl.java:260)
	at com.typesafe.config.impl.ConfigImpl.fromPathMap(ConfigImpl.java:200)
	at com.typesafe.config.ConfigFactory.parseMap(ConfigFactory.java:855)
	at com.typesafe.config.ConfigFactory.parseMap(ConfigFactory.java:866)
	at gobblin.util.ConfigUtils.propertiesToConfig(ConfigUtils.java:216)
	at gobblin.util.ConfigUtils.propertiesToConfig(ConfigUtils.java:147)
	at gobblin.runtime.JobContext.<init>(JobContext.java:136)
	at gobblin.runtime.AbstractJobLauncher.<init>(AbstractJobLauncher.java:165)
	at gobblin.runtime.AbstractJobLauncher.<init>(AbstractJobLauncher.java:136)
	at gobblin.runtime.mapreduce.MRJobLauncher.<init>(MRJobLauncher.java:147)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.<init>(CliMRJobLauncher.java:59)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
```
My Job configuration :

```
job.name=gobbKafkaHDFSJob4
job.group=GobblinKafka
job.description=Gobblin job for Kafka to HDFS
job.lock.enabled=false
job.schedule=0 0/2 * * * ?

kafka.brokers=bigd-demo-23.foo.lk:6667,bigd-demo-24.foo.lk:6667,bigd-demo-25.foo.lk:6667
topic.whitelist=ecsqueue

source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=txt
#writer.output.format=AVRO

data.publisher.type=gobblin.publisher.BaseDataPublisher

mr.job.max.mappers=1

metrics.reporting.file.enabled=true
metrics.log.dir=/bar/gobblin-kafka/metrics
metrics.reporting.file.suffix=txt

#bootstrap.with.offset=earliest
bootstrap.with.offset=latest
#reset.on.offset.out.of.range=earliest
reset.on.offset.out.of.range=latest

#fs.uri=hdfs://bigd-demo-08.foo.lk
fs.uri=hdfs://bigd-demo-09.foo.lk
writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}

mr.job.root.dir=/bar/gobblin-kafka/working
state.store.dir=/bar/gobblin-kafka/state-store
task.data.root.dir=/bar/gobblin-kafka/task-data
data.publisher.final.dir=/bar/gobblin-kafka/job-output
```
**My Local Hadoop version : 2.7.3.2.5.3.0-37**
All the Kafka brokers and HDFS URIs are accessible.

Is there anyone who can help with this issue?
Any help is so much appreciated.

*'foo', 'bar' names were replaced for intellectual property issues.

**Comment by shirshanka** [comment]
I tried this config locally (as pasted in this issue) and it didn't fail for me. 
Can you try running this in standalone mode with fs.uri=file:///  and report what happens?
