### ISSUE TITLE
Gobblin Master won't build for Hive 2.1.1

### ISSUE THREAD

**Issue by apurva-sharma** [linkedin/gobblin#1746]
A clean build off master won't build.

```
./gradlew --stacktrace --info clean build -PhadoopVersion=2.7.3 -PhiveVersion=2.1.1 -x test
```

```
Done with analysis
:gobblin-tunnel:findbugsMain (Thread[Task worker Thread 5,5,main]) completed. Took 21.033 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gobblin-hive-registration:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':gobblin-hive-registration:compileJava'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more


BUILD FAILED

Total time: 1 mins 15.899 secs
Stopped 0 compiler daemon(s).
Received result Failure[value=org.gradle.initialization.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':gobblin-hive-registration:compileJava'.] from daemon DaemonInfo{pid=26200, address=[49510300-fa44-47f1-9b30-1c22dc3f3b35 port:56415, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=false, context=DefaultDaemonContext[uid=1cc027b5-092c-4faf-a683-fd32dad7e78d,javaHome=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home,daemonRegistryDir=/Users/apsharma/.gradle/daemon,pid=26200,idleTimeout=10800000,daemonOpts=-XX:MaxPermSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xmx1024m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]} (build should be done).
```

Builds cleanly with hive 1.0.1

**Comment by apurva-sharma** [comment]
Discussed with @abti 
Looks like the MetaStore API for 2.1.1 broke the code.
```
registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java:172: error: method alter_partition in interface IMetaStoreClient cannot be applied to given types;
        client.get().alter_partition(table.getDbName(), table.getTableName(),
                    ^
  required: String,String,Partition,EnvironmentContext
  found: String,String,Partition
  reason: actual and formal argument lists differ in length
/gobblin/gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java:309: error: method alter_partition in interface IMetaStoreClient cannot be applied to given types;
            client.alter_partition(table.getDbName(), table.getTableName(), newPartition);
                  ^
  required: String,String,Partition,EnvironmentContext
  found: String,String,Partition
  reason: actual and formal argument lists differ in length
/gobblin-installer-LATEST/gobblin/gobblin-hive-registration/src/main/java/gobblin/hive/metastore/HiveMetaStoreBasedRegister.java:385: error: method alter_partition in interface IMetaStoreClient cannot be applied to given types;
      client.get().alter_partition(table.getDbName(), table.getTableName(),
```

reference (from @abti):
https://hive.apache.org/javadocs/r2.0.1/api/index.html?org/apache/hadoop/hive/metastore/IMetaStoreClient.html
and
https://hive.apache.org/javadocs/r2.1.1/api/org/apache/hadoop/hive/metastore/IMetaStoreClient.htm
