### ISSUE TITLE
Text to ORC conversion

### ISSUE THREAD

**Issue by apurva-sharma** [linkedin/gobblin#1776]
This is basically the same issue as 
https://github.com/linkedin/gobblin/issues/961

I have a converter that emits Text, and I wish the final output to be in ORC format.
Reading up the guide on:
https://gobblin.readthedocs.io/en/latest/case-studies/Writing-ORC-Data/

I set my job file as:
```
converter.classes=com.xyz.CustomTextConverter,gobblin.converter.serde.HiveSerDeConverter
serde.deserializer.type=TEXTFILE
serde.deserializer.input.format=org.apache.hadoop.mapred.TextInputFormat
serde.deserializer.output.format=org.apache.hadoop.mapred.TextOutputFormat
serde.serializer.type=ORC
fork.record.queue.capacity=1
writer.builder.class=gobblin.writer.HiveWritableHdfsDataWriterBuilder
writer.output.format=ORC
```

The issue is that there is no Serde Class corresponding to Text (since its the default file format in hive).

Using the suggestion on https://github.com/linkedin/gobblin/issues/961
I modified the Serde to CSV as:
```
serde.deserializer.type=org.apache.hadoop.hive.serde2.OpenCSVSerde
serde.serializer.type=ORC
serde.deserializer.input.format.type=org.apache.hadoop.mapred.TextInputFormat
serde.deserializer.output.format.type=org.apache.hadoop.mapred.TextOutputFormat
fork.record.queue.capacity=1
```

This throws a NPE

```
2017-04-13 19:17:06,672 ERROR [TaskExecutor-0] gobblin.runtime.Task: Task task_pull_device_logs_1492110983459_0 failed
java.lang.NullPointerException
	at org.apache.hadoop.hive.serde2.OpenCSVSerde.initialize(OpenCSVSerde.java:71)
	at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:59)
	at gobblin.converter.serde.HiveSerDeConverter.init(HiveSerDeConverter.java:43)
	at gobblin.instrumented.converter.InstrumentedConverterDecorator.init(InstrumentedConverterDecorator.java:46)
	at gobblin.runtime.TaskContext.getConverters(TaskContext.java:199)
	at gobblin.runtime.Fork.<init>(Fork.java:128)
	at gobblin.runtime.Task.run(Task.java:153)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

Any help on this would be very helpful.

Thanks,
Apurva

**Comment by aditya1105** [comment]
Corresponding pull request: 1790

**Comment by apurva-sharma** [comment]
Thanks for addressing this so quickly @aditya1105 and thanks @abti for the review

**Comment by apurva-sharma** [comment]
And looks like the serde corresponding to TEXTFILE is LazySimpleSerDe, good to know.
