### ISSUE TITLE
gobblin_0.10.0 CLI  NoSuchMethodError:org.apache.commons.cli.Option.builder(Ljava/lang/String;)

### ISSUE THREAD

**Issue by phenixmzy** [linkedin/gobblin#1863]
Error: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;
java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder(Ljava/lang/String;)Lorg/apache/commons/cli/Option$Builder;
        at gobblin.runtime.cli.CliEmbeddedGobblin.<clinit>(CliEmbeddedGobblin.java:64)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at java.lang.Class.newInstance(Class.java:379)
        at gobblin.runtime.cli.GobblinCli.main(GobblinCli.java:42)

**Comment by phenixmzy** [comment]
I am execute  $GOBBLIN_HOME/bin/gobblin.sh run in CLI, it show NoSuchMethodError and stop
