### ISSUE TITLE
Gobblin hangs when GobblinYarnAppLauncher fails to close when application fails

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#1865]
Gobblin ends up in a bad state when `GobblinYarnAppLauncher` experiences a failure while handling a `GetApplicationReportFailureEvent`.  If the `stop` call fails, the Yarn application ends up in a `FAILED` state, but the gobblin driver is still running.  The driver does not not exit or attempt to recreate the Yarn application.  This results in the job being stuck and the pipeline stops running.  Gobblin should either recover gracefully and recreate the application, or crash the driver so a supervisor process can restart it.

```
2017-05-14 20:20:59 UTC ERROR [GobblinYarnAppStatusMonitor] gobblin.yarn.GobblinYarnAppLauncher  - Failed to close the GobblinYarnAppLauncher
java.io.IOException: Failed on local exception: java.nio.channels.ClosedByInterruptException; Host Details : local host is: "host01/
127.0.0.1"; destination host is: "server":9000;
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:809)
        at org.apache.hadoop.ipc.Client.call(Client.java:1475)
        at org.apache.hadoop.ipc.Client.call(Client.java:1402)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
        at com.sun.proxy.$Proxy22.getFileInfo(Unknown Source)
        at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:752)
        at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
```

**Comment by sahilTakiar** [comment]
Looks like this happens because exceptions from `GobblinYarnAppLauncher.stop()` get logged, but not propagated. So the client will continue running.

So a simple fix would just be to propagate the exceptions so the process fails. Make sense or am I missing something?
