### ISSUE TITLE
Execution failed for task ':gobblin-modules:gobblin-couchbase:test'.]

### ISSUE THREAD

**Issue by littleRa1n** [linkedin/gobblin#1896]
Before the problem, the building process has a error : mvn is not installed. After mvn is installed, this problem is coming.So, how can i resolve it?

**Comment by littleRa1n** [comment]
gobblin.couchbase.writer.CouchbaseWriterTest.startServers FAILED
    java.lang.AssertionError: Server is not up! expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:94)
        at org.testng.Assert.failNotEquals(Assert.java:513)
        at org.testng.Assert.assertTrue(Assert.java:42)
        at gobblin.couchbase.CouchbaseTestServer.start(CouchbaseTestServer.java:105)
        at gobblin.couchbase.writer.CouchbaseWriterTest.startServers(CouchbaseWriterTest.java:89)
