### ISSUE TITLE
Running gobblin job as Oozie Mapreduce Job .

### ISSUE THREAD

**Issue by Re1tReddy** [linkedin/gobblin#1900]
Could any help me in fixing the issue . I want to run gobblin job as mapreduce via oozie .

<main-class>gobblin.runtime.mapreduce.CliMRJobLauncher</main-class>
<arg>--sysconfig</arg>
<arg>${nameNode}/user/centos/oozie-gobblin/gobblin-mapreduce.properties</arg>
<arg>--jobconfig</arg>
<arg>${nameNode}/user/centos/oozie-gobblin/job-pull.properties</arg>

This is my Workflow.xml file , i had copied all the gobblin jars to /user/centos/oozie-gobblin/lib folder . while i am run this as oozie job iam getting the following exception .

Failing Oozie Launcher, Main class [org.apache.oozie.action.hadoop.JavaMain], main() threw exception, gobblin.runtime.JobException: Job job_json-gobblin-hdfs-03_1495704992834 failed
org.apache.oozie.action.hadoop.JavaMainException: gobblin.runtime.JobException: Job job_json-gobblin-hdfs-03_1495704992834 failed
	at org.apache.oozie.action.hadoop.JavaMain.run(JavaMain.java:59)
	at org.apache.oozie.action.hadoop.LauncherMain.run(LauncherMain.java:47)
	at org.apache.oozie.action.hadoop.JavaMain.main(JavaMain.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.oozie.action.hadoop.LauncherMapper.map(LauncherMapper.java:236)
	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:54)
	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:450)

**Comment by Re1tReddy** [comment]
2017-05-26 04:11:36,601 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1492669939336_39043_m_000000_3: Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:131)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:742)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	... 7 more
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets.newConcurrentHashSet()Ljava/util/Set;
	at gobblin.configuration.SourceState.<clinit>(SourceState.java:55)
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.<init>(MRJobLauncher.java:525)
	... 12 more

**Comment by sahilTakiar** [comment]
Looks like you have the wrong version of Guava on your classpath. The master branch of Gobblin requires Guava 15.

You probably want to set `HADOOP_USER_CLASSPATH_FIRST=true`.

Would recommend taking a look at https://github.com/linkedin/gobblin/blob/master/bin/gobblin-mapreduce.sh to see how to launch a MR job.

The docs here: http://gobblin.readthedocs.io/en/latest/user-guide/Gobblin-Schedulers/#oozie also have some info on running Gobblin via Oozie.

**Comment by Re1tReddy** [comment]
HI i have already  set HADOOP_USER_CLASSPATH_FIRST=true in my .bash_profile file 
I am getting the below error ...

I also have Guava 15 jar in my class path as below . even though i am getting the below error .

2017-05-28 04:30:09,935 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: Adding hdfs://172.31.17.211:9000/user/centos/oozie-gobblin/lib/gson-2.6.2.jar to classpath
**2017-05-28 04:30:09,935 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: Adding hdfs://172.31.17.211:9000/user/centos/oozie-gobblin/lib/guava-15.0.jar to classpath**
2017-05-28 04:30:09,935 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: Adding hdfs://172.31.17.211:9000/user/centos/oozie-gobblin/lib/guava-retrying-2.0.0.jar to classpath

**2017-05-28 04:30:27,609 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : java.lang.RuntimeException: java.lang.reflect.InvocationTargetException**
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:131)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:742)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	... 7 more
**Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets.newConcurrentHashSet()Ljava/util/Set;**
	at gobblin.configuration.SourceState.<clinit>(SourceState.java:55)
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.<init>(MRJobLauncher.java:525)
	... 12 more

**Comment by Re1tReddy** [comment]
I had observed that /opt/hadoop-2.6.0/share/hadoop/tools/lib/guava-11.0.2.jar getting loaded in java.class.path , I think this is causing the issue because com.google.common.collect.Sets.newConcurrentHashSet() was not found in guava-11.0.2.jar

**Comment by Re1tReddy** [comment]
**Failing Oozie Launcher, Main class [org.apache.oozie.action.hadoop.JavaMain], main() threw exception, java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder()Lorg/apache/commons/cli/Option$Builder;
org.apache.oozie.action.hadoop.JavaMainException: java.lang.NoSuchMethodError: org.apache.commons.cli.Option.builder()Lorg/apache/commons/cli/Option$Builder;**

I have following jars in HDFS under /user/centos/oozie-gobblin/lib/ :

activation-1.1.1.jar                            gobblin-compaction-0.8.0.jar              jetty-servlet-9.2.14.v20151106.jar
annotations-2.0.1.jar                           gobblin-config-client-0.8.0.jar           jetty-util-6.1.26.jar
ant-1.9.1.jar                                   gobblin-config-core-0.8.0.jar             jetty-util-9.2.14.v20151106.jar
ant-launcher-1.9.1.jar                          gobblin-core-0.8.0.jar                    jline-0.9.94.jar
antlr-runtime-3.5.2.jar                         gobblin-data-management-0.8.0.jar         joda-time-2.9.3.jar
aopalliance-1.0.jar                             gobblin-example-0.8.0.jar                 jopt-simple-3.2.jar
apache-log4j-extras-1.2.17.jar                  gobblin-hive-registration-0.8.0.jar       jpam-1.1.jar
asm-3.1.jar                                     gobblin-kafka-0.8.0.jar                   jsch-0.1.53.jar
asm-commons-3.1.jar                             gobblin-metastore-0.8.0.jar               json-20140107.jar
asm-tree-3.1.jar                                gobblin-metrics-0.8.0.jar                 jsp-api-2.1.jar
avro-1.7.7.jar                                  gobblin-rest-api-0.8.0.jar                jsr305-3.0.0.jar
avro-ipc-1.7.7.jar                              gobblin-rest-api-data-template-0.8.0.jar  jta-1.1.jar
avro-ipc-1.7.7-tests.jar                        gobblin-rest-api-rest-client-0.8.0.jar    junit-3.8.1.jar
avro-mapred-1.7.7-hadoop2.jar                   gobblin-rest-client-0.8.0.jar             kafka_2.11-0.8.2.2.jar
aws-java-sdk-applicationautoscaling-1.11.8.jar  gobblin-rest-server-0.8.0.jar             kafka-avro-serializer-2.0.1.jar
aws-java-sdk-autoscaling-1.11.8.jar             gobblin-runtime-0.8.0.jar                 kafka-clients-0.8.2.2.jar
aws-java-sdk-core-1.11.8.jar                    gobblin-test-harness-0.8.0.jar            kafka-json-serializer-2.0.1.jar
aws-java-sdk-ec2-1.11.8.jar                     gobblin-tunnel-0.8.0.jar                  kafka-schema-registry-client-2.0.1.jar
aws-java-sdk-iam-1.11.8.jar                     gobblin-utility-0.8.0.jar                 libfb303-0.9.0.jar
aws-java-sdk-kms-1.11.8.jar                     gobblin-yarn-0.8.0.jar                    libthrift-0.9.3.jar
aws-java-sdk-s3-1.11.8.jar                      groovy-all-2.1.6.jar                      li-jersey-uri-1.15.9.jar
aws-java-sdk-sts-1.11.8.jar                     gson-2.6.2.jar                            log4j-1.2.17.jar
azkaban-2.5.0.jar                               guava-15.0.jar                            lombok-1.16.8.jar
bcpg-jdk15on-1.52.jar                           guava-retrying-2.0.0.jar                  lz4-1.2.0.jar
bcprov-jdk15on-1.52.jar                         guice-4.0.jar                             mail-1.4.1.jar
bonecp-0.8.0.RELEASE.jar                        guice-servlet-3.0.jar                     maven-scm-api-1.4.jar
bsh-2.0b4.jar                                   hamcrest-core-1.1.jar                     maven-scm-provider-svn-commons-1.4.jar
c3p0-0.9.1.1.jar                                helix-core-0.6.6-SNAPSHOT.jar             maven-scm-provider-svnexe-1.4.jar
calcite-avatica-1.2.0-incubating.jar            hive-ant-1.0.1.jar                        metrics-core-2.2.0.jar
calcite-core-1.2.0-incubating.jar               hive-common-1.0.1.jar                     metrics-core-3.1.0.jar
calcite-linq4j-1.2.0-incubating.jar             hive-exec-1.0.1-core.jar                  metrics-graphite-3.1.0.jar
cglib-nodep-2.2.jar                             hive-jdbc-1.0.1.jar                       metrics-jvm-3.1.0.jar
codemodel-2.2.jar                               hive-metastore-1.0.1.jar                  mina-core-1.1.7.jar
common-config-2.0.1.jar                         hive-serde-1.0.1.jar                      mockito-core-1.10.19.jar
commons-cli-1.3.1.jar                           hive-service-1.0.1.jar                    mysql-connector-java-5.1.38.jar
commons-codec-1.10.jar                          hive-shims-0.20-1.0.1.jar                 netty-3.2.3.Final.jar
commons-collections-3.2.1.jar                   hive-shims-0.20S-1.0.1.jar                netty-3.7.0.Final.jar
commons-compiler-2.7.6.jar                      hive-shims-0.23-1.0.1.jar                 objenesis-2.1.jar
commons-compress-1.10.jar                       hive-shims-1.0.1.jar                      okhttp-2.4.0.jar
commons-configuration-1.10.jar                  hive-shims-common-1.0.1.jar               okio-1.4.0.jar
commons-daemon-1.0.13.jar                       hive-shims-common-secure-1.0.1.jar        opencsv-2.3.jar
commons-dbcp-1.4.jar                            httpclient-4.5.2.jar                      org.apache.oltu.oauth2.client-1.0.2.jar
commons-el-1.0.jar                              httpcore-4.4.4.jar                        org.apache.oltu.oauth2.common-1.0.2.jar
commons-email-1.4.jar                           influxdb-java-2.1.jar                     paranamer-2.3.jar
commons-httpclient-3.1.jar                      jackson-annotations-2.6.0.jar             parseq-1.3.6.jar
commons-io-2.5.jar                              jackson-core-2.6.6.jar                    pegasus-common-1.15.9.jar
commons-lang-2.6.jar                            jackson-core-asl-1.9.13.jar               pentaho-aggdesigner-algorithm-5.1.5-jhyde.jar
commons-lang3-3.4.jar                           jackson-databind-2.6.6.jar                plexus-utils-1.5.6.jar
commons-logging-1.2.jar                         jackson-dataformat-cbor-2.6.6.jar         protobuf-java-2.5.0.jar
commons-math3-3.5.jar                           jackson-jaxrs-1.8.3.jar                   quartz-2.2.3.jar
commons-net-3.1.jar                             jackson-mapper-asl-1.9.13.jar             r2-1.15.9.jar
commons-pool-1.5.4.jar                          jackson-xc-1.8.3.jar                      reflections-0.9.10.jar
commons-pool2-2.4.2.jar                         janino-2.7.6.jar                          regexp-1.3.jar
commons-vfs2-2.0.jar                            jansi-1.11.jar                            restli-client-1.15.9.jar
common-utils-2.0.1.jar                          jasper-compiler-5.5.23.jar                restli-common-1.15.9.jar
config-1.2.1.jar                                jasper-runtime-5.5.23.jar                 restli-docgen-1.15.9.jar
curator-client-2.10.0.jar                       jasypt-1.9.2.jar                          restli-netty-standalone-1.15.9.jar
curator-framework-2.10.0.jar                    javassist-3.18.2-GA.jar                   restli-server-1.15.9.jar
curator-recipes-2.10.0.jar                      javax.inject-1.jar                        restli-tools-1.15.9.jar
d2-1.15.9.jar                                   javax.mail-1.5.2.jar                      retrofit-1.9.0.jar
data-1.15.9.jar                                 java-xmlbuilder-0.4.jar                   scala-library-2.11.8.jar
datanucleus-api-jdo-3.2.6.jar                   javax.servlet-api-3.1.0.jar               scala-parser-combinators_2.11-1.0.2.jar
datanucleus-core-3.2.10.jar                     jaxb-api-2.2.2.jar                        scala-xml_2.11-1.0.2.jar
datanucleus-rdbms-3.2.9.jar                     jaxb-impl-2.2.3-1.jar                     servlet-api-2.5-20081211.jar
data-transform-1.15.9.jar                       jcommander-1.48.jar                       servlet-api-2.5.jar
degrader-1.15.9.jar                             jdo2-api-2.1.jar                          slf4j-api-1.7.21.jar
derby-10.12.1.1.jar                             jdo-api-3.0.1.jar                         slf4j-log4j12-1.7.21.jar
eigenbase-properties-1.1.5.jar                  jersey-core-1.9.jar                       snappy-0.3.jar
flyway-core-3.2.1.jar                           jersey-guice-1.9.jar                      snappy-java-1.1.1.7.jar
generator-1.15.9.jar                            jersey-json-1.9.jar                       ST4-4.0.4.jar
geronimo-annotation_1.0_spec-1.1.1.jar          jersey-server-1.9.jar                     stax-api-1.0.1.jar
geronimo-jaspic_1.0_spec-1.0.jar                jets3t-0.9.0.jar                          stax-api-1.0-2.jar
geronimo-jpa_3.0_spec-1.0.jar                   jettison-1.1.jar                          testng-6.9.10.jar
geronimo-jta_1.1_spec-1.1.1.jar                 jetty-6.1.26.jar                          transaction-api-1.1.jar
gobblin-admin-0.8.0.jar                         jetty-all-7.6.0.v20120127.jar             velocity-1.7.jar
gobblin-api-0.8.0.jar                           jetty-http-9.2.14.v20151106.jar           xmlenc-0.52.jar
gobblin-aws-0.8.0.jar                           jetty-io-9.2.14.v20151106.jar             zkclient-0.7.jar
gobblin-azkaban-0.8.0.jar                       jetty-security-9.2.14.v20151106.jar       zookeeper-3.4.6.jar
gobblin-cluster-0.8.0.jar                       jetty-server-9.2.14.v20151106.jar

**Comment by sahilTakiar** [comment]
I would take a look at https://github.com/linkedin/gobblin/tree/master/gobblin-oozie/src/test/resources/local - it has example `workflow.xml` files you can use for Oozie.

**Comment by Re1tReddy** [comment]
@sahilTakiar I am also using same workflow.xml , but instead of CliLocalJobLauncher i am using CliMRJobLauncher , that's only the difference . 

I am specifying oozie.launcher.mapreduce.user.classpath.first = true , but some how it is not picking the gobblin jars in the class path instead it is picking the hadoop jars 

**That why i am getting the below error ,It is picking the Guva jar  from hadoop lib not from gobblin lib . Attached the logs for your reference **
[log1.txt](https://github.com/linkedin/gobblin/files/1040225/log1.txt)
[log2.txt](https://github.com/linkedin/gobblin/files/1040226/log2.txt)




**2017-05-30 10:33:08,950 INFO [AsyncDispatcher event handler] org.apache.hadoop.mapreduce.v2.app.job.impl.TaskAttemptImpl: Diagnostics report from attempt_1492669939336_41538_m_000000_2: Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException**
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:131)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:742)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1628)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.util.ReflectionUtils.newInstance(ReflectionUtils.java:129)
	... 7 more
**Caused by: java.lang.NoSuchMethodError: com.google.common.collect.Sets.newConcurrentHashSet()Ljava/util/Set;**
	at gobblin.configuration.SourceState.<clinit>(SourceState.java:55)
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.<init>(MRJobLauncher.java:525)
	... 12 more

**Comment by Re1tReddy** [comment]
@sahilTakiar I had fixed the issue , I am using gobblin 0.8.0 version . In gobblin.runtime.mapreduce.MRJobLauncher.java class we have method called 

**private void prepareHadoopJob(List<WorkUnit> workUnits){**
I have added the below line in this method and compiled the code my problem fixed :

**this.job.getConfiguration().set("mapreduce.job.user.classpath.first", "true");**

Actually the same  has been  implemented in gobblin 0.10.0

**Comment by Re1tReddy** [comment]
fixed the issue by specifying the following line in job-pull.properties/.pull  file 
mapreduce.job.user.classpath.first=true
