### ISSUE TITLE
How the Gobblin on Yarn Continued consume Kafka

### ISSUE THREAD

**Issue by phenixmzy** [linkedin/gobblin#1911]
I want to use Gobblin on Yarn Long-Running the Job to consume Kafka and write to HDFS.
But when i start gobblin-yarn.sh, the job just consume some kafka data to HDFS, afterwards push to kafka data all cant't be consume and write to HDFS.
My job config has problem? 

my-job-config.pull
job.name=GobblinKafkaQuickStart
job.group=GobblinKafka
job.description=Gobblin quick start job for Kafka
job.lock.enabled=false
#job.schedule=0 0/10 * * * * ?
kafka.brokers=my-bigdata-32-201.meizu.com:9092
topic.whitelist=test
source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=txt

data.publisher.type=gobblin.publisher.BaseDataPublisher

metrics.reporting.file.enabled=true
metrics.log.dir=/gobblin-kafka/metrics
metrics.reporting.file.suffix=txt

bootstrap.with.offset=earliest

fs.uri=hdfs://mycluster
writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}

mr.job.root.dir=/gobblin-kafka/working
state.store.dir=/gobblin-kafka/state-store
task.data.root.dir=/gobblin-kafka/task-data
data.publisher.final.dir=/gobblintest/job-output

**Comment by sahilTakiar** [comment]
I think you need to un-comment the `job.schedule` config. Otherwise your job will only run once, and won't read any new data written to Kafka.

**Comment by phenixmzy** [comment]
@sahilTakiar thanks!
when i open the job.schedule=0 0/5 * * * ? , the kafka data still can't  write to HDFS
and the log Exception Message:
 2017-06-02 15:10:00 CST INFO  [DefaultQuartzScheduler_Worker-2] gobblin.cluster.GobblinHelixJobLauncher  - Submitted job job_GobblinKafkaQuickStart_1496387100091 to Helix
2017-06-02 15:11:00 CST WARN  [TaskStateCollectorService RUNNING] gobblin.runtime.TaskStateCollectorService  - No output task state files found in hdfs://mzcluster/user/yarn/GobblinYarn/application_1496386839375_0001/_taskstates/job_GobblinKafkaQuickStart_1496387100091
....
....
2017-06-02 15:15:00 CST INFO  [TaskStateCollectorService STARTING] gobblin.runtime.TaskStateCollectorService  - Starting the TaskStateCollectorService
2017-06-02 15:15:00 CST WARN  [TaskStateCollectorService RUNNING] gobblin.runtime.TaskStateCollectorService  - No output task state files found in hdfs://mzcluster/user/yarn/GobblinYarn/application_1496386839375_0001/_taskstates/job_GobblinKafkaQuickStart_1496387100091
2017-06-02 15:15:00 CST WARN  [DefaultQuartzScheduler_Worker-3] gobblin.util.ParallelRunner  - Task failed: Serialize state to store job_GobblinKafkaQuickStart_1496387100091 file multitask_GobblinKafkaQuickStart_1496387100091_0.mwu
## org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename hdfs://mzcluster/user/yarn/GobblinYarn/application_1496386839375_0001/_workunits/job_GobblinKafkaQuickStart_1496387100091/_tmp_multitask_GobblinKafkaQuickStart_1496387100091_0.mwu to hdfs://mzcluster/user/yarn/GobblinYarn/application_1496386839375_0001/_workunits/job_GobblinKafkaQuickStart_1496387100091/multitask_GobblinKafkaQuickStart_1496387100091_0.mwu: dst already exists
	at gobblin.util.HadoopUtils.renamePath(HadoopUtils.java:219)
	at gobblin.util.HadoopUtils.renamePath(HadoopUtils.java:201)
	at gobblin.metastore.FsStateStore.put(FsStateStore.java:176)
	at gobblin.cluster.GobblinHelixJobLauncher$2.call(GobblinHelixJobLauncher.java:324)
	at gobblin.cluster.GobblinHelixJobLauncher$2.call(GobblinHelixJobLauncher.java:321)
	at gobblin.util.executors.MDCPropagatingCallable.call(MDCPropagatingCallable.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by phenixmzy** [comment]
@sahilTakiar thanks!
when i un-comment the job.schedule and set 0 0/10 * * * ?, new data still can't written to HDFS.
the log show FileAlreadyExistsException.
017-06-02 16:40:00 CST WARN  [DefaultQuartzScheduler_Worker-3] gobblin.util.ParallelRunner  - Task failed: Serialize state to store job_GobblinKafkaQuickStart_1496391600093 file multitask_GobblinKafkaQuickStart_1496391600093_0.mwu
org.apache.hadoop.fs.FileAlreadyExistsException: Failed to rename hdfs://mzcluster/user/yarn/GobblinYarn/application_1496386839375_0004/_workunits/job_GobblinKafkaQuickStart_1496391600093/_tmp_multitask_GobblinKafkaQuickStart_1496391600093_0.mwu to hdfs://mzcluster/user/yarn/GobblinYarn/application_1496386839375_0004/_workunits/job_GobblinKafkaQuickStart_1496391600093/multitask_GobblinKafkaQuickStart_1496391600093_0.mwu: dst already exists
