### ISSUE TITLE
Failed job emails

### ISSUE THREAD

**Issue by akshayn1107** [linkedin/gobblin#299]
I have appended the following to my gobblin job config:

```
email.alert.enabled=true
email.notification.enabled=true
email.host=localhost
email.smtp.port=25
email.from=<from-email>
email.tos=<to-emails>

# these should be default values
workunit.retry.enabled=true
workunit.retry.policy=always
task.maxretries=5
task.retry.intervalinsec=60
job.max.failures=0
```

When a job successfully completes, I do receive emails. However, on job failures, I don't receive any emails. Furthermore, if a task in a job fails due to an exception, I get a job completion email (not a job failed email). 

On a potentially related note, failed jobs aren't automatically being retried.

**Comment by liyinan926** [comment]
To enable alert emails on job failures, you need to set `email.alert.enabled=true`. Gobblin doesn't retry failed jobs. It does retry failed tasks up to a configurable number of times (default is 5).

**Comment by liyinan926** [comment]
Are you running the latest version of Gobblin?

**Comment by liyinan926** [comment]
I found a bug that may cause the issue with alert emails and created this PR https://github.com/linkedin/gobblin/pull/300.

**Comment by liyinan926** [comment]
PR #300 has been merged. Please let us know if you are still not receiving alert emails on job failures with the fix.

**Comment by akshayn1107** [comment]
So I've tried two ways of making the job fail: 1) specifying a bad kafka cluster (which causes the work units to not be created since it can't connect to kafka) and 2) specifying a bad s3 bucket so the job completes but the publisher fails. Both times no email gets sent.

**Comment by liyinan926** [comment]
@akshayn1107 Are you using `gobblin-mapreduce.sh` to launch jobs?

**Comment by akshayn1107** [comment]
no, we're using gobblin in standalone mode

**Comment by liyinan926** [comment]
OK, did you see `JobException: Job ... failed` in the logs? Can you share the logs?

**Comment by akshayn1107** [comment]
Below is the stack trace if I specify a bad bucket (causing the publisher to fail):

```
2015-08-25 16:34:13 PDT ERROR [JobScheduler-0] gobblin.runtime.AbstractJobLauncher  277 - Failed to launch and run job job_KafkaPageView_1440545637565: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1E4BBA9F8C6C7847), S3 Extended Request ID: ywBfWjNk3xSrLeOlZdwcfjiHpcyqBs/uvurHc5+JAiiUSwIPRU7TFiJdYA+wO4+fv0ooe/n2h+I=
com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1E4BBA9F8C6C7847), S3 Extended Request ID: ywBfWjNk3xSrLeOlZdwcfjiHpcyqBs/uvurHc5+JAiiUSwIPRU7TFiJdYA+wO4+fv0ooe/n2h+I=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1160)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:748)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:2659)
	at nerdwallet.gobblin.publisher.BaseS3Publisher.sendS3Data(BaseS3Publisher.java:95)
	at nerdwallet.gobblin.publisher.KafkaS3Publisher.publishData(KafkaS3Publisher.java:52)
	at gobblin.publisher.DataPublisher.publish(DataPublisher.java:60)
	at gobblin.runtime.JobContext.commitDataset(JobContext.java:305)
	at gobblin.runtime.JobContext.commit(JobContext.java:240)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:271)
	at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:269)
	at gobblin.scheduler.JobScheduler$NonScheduledJobRunner.run(JobScheduler.java:476)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233415_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233415_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233411_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233411_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233416_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233416_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233412_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233412_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233417_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233417_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233413_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233413_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233414_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233414_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233418_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233418_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233419_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233419_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  174 - Cleaning up staging directory /srv/nerdwallet/gobblin-workspace/work/task-staging/KAFKA/PageViewEvent/20150825233420_append
2015-08-25 16:34:13 PDT INFO  [JobScheduler-0] gobblin.util.JobLauncherUtils  180 - Cleaning up output directory /srv/nerdwallet/gobblin-workspace/work/task-output/KAFKA/PageViewEvent/20150825233420_append
2015-08-25 16:34:13 PDT ERROR [JobScheduler-0] gobblin.scheduler.JobScheduler  276 - Failed to launch and run job KafkaPageView
gobblin.runtime.JobException: Failed to launch and run job job_KafkaPageView_1440545637565
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:278)
	at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:269)
	at gobblin.scheduler.JobScheduler$NonScheduledJobRunner.run(JobScheduler.java:476)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1E4BBA9F8C6C7847), S3 Extended Request ID: ywBfWjNk3xSrLeOlZdwcfjiHpcyqBs/uvurHc5+JAiiUSwIPRU7TFiJdYA+wO4+fv0ooe/n2h+I=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1160)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:748)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:2659)
	at nerdwallet.gobblin.publisher.BaseS3Publisher.sendS3Data(BaseS3Publisher.java:95)
	at nerdwallet.gobblin.publisher.KafkaS3Publisher.publishData(KafkaS3Publisher.java:52)
	at gobblin.publisher.DataPublisher.publish(DataPublisher.java:60)
	at gobblin.runtime.JobContext.commitDataset(JobContext.java:305)
	at gobblin.runtime.JobContext.commit(JobContext.java:240)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:271)
	... 7 more
2015-08-25 16:34:13 PDT INFO  [TaskExecutor STOPPING] gobblin.runtime.TaskExecutor  135 - Stopping the task executor
2015-08-25 16:34:13 PDT INFO  [LocalTaskStateTracker2 STOPPING] gobblin.runtime.AbstractTaskStateTracker  71 - Stopping the task state tracker
2015-08-25 16:34:13 PDT ERROR [JobScheduler-0] gobblin.scheduler.JobScheduler$NonScheduledJobRunner  478 - Failed to run job KafkaPageView
gobblin.runtime.JobException: Failed to launch and run job KafkaPageView
	at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:277)
	at gobblin.scheduler.JobScheduler$NonScheduledJobRunner.run(JobScheduler.java:476)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: gobblin.runtime.JobException: Failed to launch and run job job_KafkaPageView_1440545637565
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:278)
	at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:269)
	... 6 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket does not exist (Service: Amazon S3; Status Code: 404; Error Code: NoSuchBucket; Request ID: 1E4BBA9F8C6C7847), S3 Extended Request ID: ywBfWjNk3xSrLeOlZdwcfjiHpcyqBs/uvurHc5+JAiiUSwIPRU7TFiJdYA+wO4+fv0ooe/n2h+I=
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1160)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:748)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:467)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:302)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3672)
	at com.amazonaws.services.s3.AmazonS3Client.initiateMultipartUpload(AmazonS3Client.java:2659)
	at nerdwallet.gobblin.publisher.BaseS3Publisher.sendS3Data(BaseS3Publisher.java:95)
	at nerdwallet.gobblin.publisher.KafkaS3Publisher.publishData(KafkaS3Publisher.java:52)
	at gobblin.publisher.DataPublisher.publish(DataPublisher.java:60)
	at gobblin.runtime.JobContext.commitDataset(JobContext.java:305)
	at gobblin.runtime.JobContext.commit(JobContext.java:240)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:271)
	... 7 more
```

**Comment by liyinan926** [comment]
OK, I know what's going on here and I will fix it.

**Comment by liyinan926** [comment]
Created PR #309.

**Comment by akshayn1107** [comment]
Sweet, it looks like its fixed now. Thanks!

**Comment by liyinan926** [comment]
Cool. Thanks for reporting this!
