### ISSUE TITLE
Failing to clean up staging data

### ISSUE THREAD

**Issue by ahollenbach** [linkedin/gobblin#313]
I'm running into an issue where any number of threads above one will cause the `FileBasedSource` to fail when trying to clean up a regular fs (not Hadoop). From what I can tell, it appends numerous delete tasks for the same directory to the future queue, and `HadoopUtils` throws an error if the delete fails (which it will fail if the directory no longer exists). This can be mitigated by setting `parallel.runner.threads=1`

Alternatively, I was able to prevent the error from showing up by setting a `source.max.number.of.partitions` to a value <= 4 (resulting in about 35 files per partition), although occasionally the job would fail with the number of partitions equal to 4, and sometimes not, making this not a valid solution and likely not the cause.

Is the parallelization designed to support non-Hadoop filesystems?

Here's the stack trace for where things go wrong. Everything is publishing correctly, it just is failing to clean up the job once finished.

```java
2015-08-26 15:31:39 PDT ERROR [JobScheduler-0] gobblin.runtime.AbstractJobLauncher  576 - Failed to clean staging data
java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: Failed to delete: /gobblin-workspace/work/task-output/S3Source/20150826222842_append
       at gobblin.util.ParallelRunner.close(ParallelRunner.java:259)
       at com.google.common.io.Closer.close(Closer.java:214)
       at gobblin.runtime.AbstractJobLauncher.cleanupStagingData(AbstractJobLauncher.java:574)
       at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:299)
       at gobblin.scheduler.JobScheduler.runJob(JobScheduler.java:269)
       at gobblin.scheduler.JobScheduler$NonScheduledJobRunner.run(JobScheduler.java:476)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
       at java.util.concurrent.FutureTask.run(FutureTask.java:262)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Failed to delete: /gobblin-workspace/work/task-output/S3Source/20150826222842_append
       at java.util.concurrent.FutureTask.report(FutureTask.java:122)
       at java.util.concurrent.FutureTask.get(FutureTask.java:188)
       at gobblin.util.ParallelRunner.close(ParallelRunner.java:254)
       ... 10 more
Caused by: java.io.IOException: Failed to delete: /gobblin-workspace/work/task-output/S3Source/20150826222842_append
       at gobblin.util.HadoopUtils.deletePath(HadoopUtils.java:86)
       at gobblin.util.ParallelRunner$4.call(ParallelRunner.java:213)
       at gobblin.util.ParallelRunner$4.call(ParallelRunner.java:210)
       ... 4 more
```

**Comment by zliu41** [comment]
@ahollenbach thanks for posting. This is a bug we also identified a few weeks back. We'll have it fixed.

**Comment by chavdar** [comment]
A fix has been merged. @ahollenbach Could you verify?

**Comment by ahollenbach** [comment]
After some preliminary testing, everything appears to be running smoothly. Thanks for the fix.
