### ISSUE TITLE
gobblin won't work with Hadoop 2.3.0-cdh5.0.1 (cloudera)

### ISSUE THREAD

**Issue by iamwrong** [linkedin/gobblin#367]
I compiled Gobblin with Hadoop 2.3.0-cdh5.0.1 and it does not work

$./gradlew clean build -PuseHadoop2 -PhadoopVersion=2.3.0-cdh5.0.1

when i try to run the wikipedia example on the hadoop cluster i get this:

$./gobblin-mapreduce.sh --jt jobtracker-url.de:9001 --fs hdfs://hdfs-url.de:8020 --workdir hdfs:///jobresults --conf /home/iamwrong/git/gobblin/gobblin-example/src/main/resources/wikiConfig/wikipedia.pull

i get the above error:

WARN [JobContext] Property task.data.root.dir is missing.
Error: java.io.IOException: Not all tasks running in mapper attempt_1442225331770_36375_m_000000_0 completed successfully
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.runWorkUnits(MRJobLauncher.java:731)
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.run(MRJobLauncher.java:629)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:764)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:340)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)

**Comment by liyinan926** [comment]
@iamwrong to figure out what's actually with the job you need to check the logs of the mappers.

**Comment by liyinan926** [comment]
@iamwrong are you able to figure out why your job was failing?

**Comment by samirabdou** [comment]
I came across the same issue:

**Running:**
```bash
$=>./gobblin-mapreduce.sh --workdir /tmp/gobblin-workdir --conf ~/gobblin-jobs/gobblin-jobs/wikipedia.pull
```

**Leads to:**
```Java
Error: java.io.IOException: Not all tasks running in container attempt_1448218067387_0004_m_000000_0 completed successfully
    at gobblin.runtime.AbstractJobLauncher.runWorkUnits(AbstractJobLauncher.java:585)
    at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.run(MRJobLauncher.java:584)
    at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
    at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:164)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
    at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**The mappers logs show:**
```Java
java.lang.RuntimeException: java.lang.ClassNotFoundException: gobblin.example.wikipedia.WikipediaSource
        at gobblin.runtime.TaskContext.getSource(TaskContext.java:97)
        at gobblin.runtime.TaskContext.getExtractor(TaskContext.java:123)
        at gobblin.runtime.Task.run(Task.java:126)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**I solved the issue by adding the gobblin-example.jar to the classpath:**
```bash
$=>./gobblin-mapreduce.sh --workdir /tmp/gobblin-workdir --jars ../lib/gobblin-example.jar --conf ~/gobblin-jobs/wikipedia.pull
```

It seems that when jars are not specified explicitly, it doesn’t get added to the classpath!

**Comment by sheikh-aslam** [comment]
Hello Everyone,

I am facing same issue while running my Wikipedia example in MapReduce mode.
i try to run program with following command but still getting the same error(java.lang.Class NotFoundException: gobblin.example.wikipedia.WikipediaSource..at gobblin.runtime.TaskContext.getSource)
Anyone please help me out to solve the error
 
bin/gobblin-mapreduce.sh start --workdir /home/cloudera/gobblin/wikipediaExp/ --jars /home/cloudera/gobblin/gobblin-dist/lib/wikipedia.jar --conf /home/cloudera/gobblin/wikipediaExp/conf/wikipedia.pull  --logdir /home/cloudera/gobblin/wikipediaExp/log/ 

I think there is some problem with the jar(wikipedia.jar)i am using. 
(I am using gobblin 0.8 release in cloudera-quickstart-vm-5.5.0-0-vmware)
[myDocuments.tar.gz](https://github.com/linkedin/gobblin/files/518446/myDocuments.tar.gz)
