### ISSUE TITLE
Is document wrong or my setup?

### ISSUE THREAD

**Issue by prasadnh** [linkedin/gobblin#382]
https://github.com/linkedin/gobblin/wiki/Getting%20Started

I get error while running bin/gobblin-standalone.sh restart
Oct 12, 2015 3:29:20 PM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service JobScheduler [FAILED] has failed in the STARTING state.
java.lang.RuntimeException: Found more than one .properties file in directory: /home/ubuntu/gobblin-dist/conf
        at gobblin.util.SchedulerUtils.loadJobConfigsRecursive(SchedulerUtils.java:192)
        at gobblin.util.SchedulerUtils.loadJobConfigs(SchedulerUtils.java:84)
        at gobblin.scheduler.JobScheduler.loadLocalJobConfigs(JobScheduler.java:368)
        at gobblin.scheduler.JobScheduler.scheduleLocallyConfiguredJobs(JobScheduler.java:357)
        at gobblin.scheduler.JobScheduler.startUp(JobScheduler.java:141)
        at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
        at java.lang.Thread.run(Thread.java:745)

Exception in thread "JobScheduler STARTING" java.lang.RuntimeException: Found more than one .properties file in directory: /home/ubuntu/gobblin-dist/conf
        at gobblin.util.SchedulerUtils.loadJobConfigsRecursive(SchedulerUtils.java:192)
        at gobblin.util.SchedulerUtils.loadJobConfigs(SchedulerUtils.java:84)
        at gobblin.scheduler.JobScheduler.loadLocalJobConfigs(JobScheduler.java:368)
        at gobblin.scheduler.JobScheduler.scheduleLocallyConfiguredJobs(JobScheduler.java:357)
        at gobblin.scheduler.JobScheduler.startUp(JobScheduler.java:141)
        at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
        at java.lang.Thread.run(Thread.java:745)
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /gobblin-current.log (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
        at org.apache.log4j.rolling.RollingFileAppender.activateOptions(RollingFileAppender.java:180)
        at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:295)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:176)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:191)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:523)
        at org.apache.log4j.xml.DOMConfigurator.parseRoot(DOMConfigurator.java:492)
        at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:1006)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:872)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
        at gobblin.scheduler.SchedulerDaemon.<clinit>(SchedulerDaemon.java:51)
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /gobblin-current.log (Permission denied)

**Comment by liyinan926** [comment]
@prasadnh The problem here is you are either missing a required command-line argument `--conf` or incorrectly pointing it to `gobblin-dist/conf`. The argument `--conf` is used to specify the path to the job config file directory, whereas `gobblin-dist/conf` is for system configs. Please take a look at https://github.com/linkedin/gobblin/wiki/Gobblin%20Deployment#Standalone-Deployment.

**Comment by prasadnh** [comment]
Thanks... I can see the process is running. but I see above error even with --conf and I don't see any logs generated except nohup.out (BTW I am new to this area...trying different kafka/hdfs ingestion tools).

ubuntu@ip-10-201-5-35:~/gobblin/gobblin-dist$ ps aux | grep gobblin
ubuntu    8799  5.7  1.2 3500484 98780 pts/3   Sl   17:06   0:01 /usr/lib/jvm/default-java/bin/java -Xmx2g -Xms1g -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/ -Xloggc:/gobblin-gc.log -Dgobblin.logs.dir= -Dlog4j.configuration=file:///home/ubuntu/gobblin/gobblin-dist/conf/log4j-standalone.xml -cp /home/ubuntu/gobblin/gobbli -dist/lib/activation-1.1.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/ant-1.9.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/ant-launcher-1.9.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/antlr-runtime-3.5.2.jar:/home/ubuntu/gobblin/gobbli -dist/lib/aopalliance-1.0.jar:/home/ubuntu/gobblin/gobblin-dist/lib/apache-log4j-extras-1.2.17.jar:/home/ubuntu/gobblin/gobblin-dist/lib/asm-3.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/asm-commons-3.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/asm-tree-3.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/avro-1.7.7.jar:/home/ubuntu/gobblin/gobblin-dist/lib/avro-ipc-1.7.7.jar:/home/ubuntu/gobblin/gobblin-dist/lib/avro-ipc-1.7.7-tests.jar:/home/ubuntu/gobblin/gobblin-dist/lib/avro-mapred-1.7.7-hadoop2.jar:/home/ubuntu/gobblin/gobblin-dist/lib/azkaban-2.5.0.jar:/home/ubuntu/gobblin/gobblin-dist/lib/bonecp-0.8.0.RELEASE.jar:/home/ubuntu/gobblin/gobblin-dist/lib/c3p0-0.9.1.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/cglib-2.2.1-v20090111.jar:/home/ubuntu/gobblin/gobblin-dist/lib/cglib-nodep-2.2.jar:/home/ubuntu/gobblin/gobblin-dist/lib/codemodel-2.2.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-cli-1.3.1.jar:/home/ubuntu/gobblin gobblin-dist/lib/commons-codec-1.10.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-collections-3.2.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-compress-1.4.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-configuration-1.10.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-daemon-1.0.13.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-dbcp-1.4.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-el-1.0.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-email-1.4.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-httpclient-3.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-io-2.4.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-lang-2.6.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-lang3-3.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-logging-1.2.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-math-2.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-math3-3.5.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-net-3.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-pool-1.5.4.jar:/home/ubuntu/gobblin/gobblin-dist/lib/commons-vfs2-2.0.jar:/home/ubuntu/gobblin/gobblin-dist/lib/config-1.2.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/d2-1.15.9.jar:/home/ubuntu/gobblin/gobblin-dist/lib/data-1.15.9.jar:/home/ubuntu/gobblin/gobblin-dist/lib/datanucleus-api-jdo-3.2.6.jar:/home/ubuntu/gobblin/gobblin-dist/lib/datanucleus-core-4.1.2.jar:/home/ubuntu/gobblin/gobbli -dist/lib/datanucleus-rdbms-4.1.2.jar:/home/ubuntu/gobblin/gobblin-dist/lib/data-transform-1.15.9.jar:/home/ubuntu/gobblin/gobblin-dist/lib/degrader-1.15.9.jar:/home/ubuntu/gobblin/gobblin-dist/lib/derby-10.11.1.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/dnsns.jar:/home/ubuntu/gobblin/gobblin-dist/lib/generator-1.15.9.jar:/home/ubuntu/gobblin/gobblin-dist/lib/geronimo-annotation_1.0_spec-1.1.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/geronimo-jaspic_1.0_spec-1.0.jar:/home/ubuntu/gobblin/gobblin-dist/lib/geronimo-jpa_3.0_spec-1.0.jar:/home/ubuntu/gobblin/gobblin-dist/lib/geronimo-jta_1.1_spec-1.1.1.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gmbal-api-only-3.0.0-b023.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-api.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-azkaban.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-compaction.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-core.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-data-management.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-example.jar:/home/ubuntu/gobblin/gobblin-dist/lib/gobblin-metastore.jar:/home/ubuntu/gobblin/gobblin
ubuntu    8823  0.0  0.0  10460   940 pts/3    S+   17:06   0:00 grep --color=auto gobblin

**Comment by sahilTakiar** [comment]
Hey @prasadnh,

There seems to be a couple of issues:

1: You have multiple files that end in `.properties` under `/home/ubuntu/gobblin-dist/conf` you need to remove all but one. Can you send us the contents of that directory? If it is the same as https://github.com/linkedin/gobblin/tree/master/conf then you can remove the file `gobblin-mapreduce.properties`.

2: You are getting a `Permission Denied` exception because the process is trying to write to `/gobblin-current.log`. When launching the job you need to add the option `--logdir` and specify a directory you have write permissions for. All logs for the job will be written to that directory.

**Comment by prasadnh** [comment]
Thanks... i see three properties files like standlone, quartz, Mapreduce and log4j. do you think I need to move all these?
content of directory is 
total 44
-rw-rw-r-- 1 ubuntu ubuntu   627 Oct 12 14:56 reference.conf
-rw-rw-r-- 1 ubuntu ubuntu   149 Oct 12 14:56 quartz.properties
-rwxrwxr-x 1 ubuntu ubuntu  1307 Oct 12 14:56 log4j-yarn.properties
-rw-rw-r-- 1 ubuntu ubuntu   581 Oct 12 14:56 log4j.xml
-rw-rw-r-- 1 ubuntu ubuntu  1024 Oct 12 14:56 log4j-standalone.xml
-rw-rw-r-- 1 ubuntu ubuntu  1085 Oct 12 14:56 log4j-compaction.xml
-rwxrwxr-x 1 ubuntu ubuntu    64 Oct 12 14:56 gobblin-env.sh
-rw-rw-r-- 1 ubuntu ubuntu  1992 Oct 12 14:56 application.conf
-rw-rw-r-- 1 ubuntu ubuntu   919 Oct 13 14:42 kafka.pull
-rw-rw-r-- 1 ubuntu ubuntu  1474 Oct 14 16:32 gobblin-standalone.properties
-rw------- 1 ubuntu ubuntu 11425 Oct 14 16:37 nohup.out


I still get same properties error even after moving all properties files (except standalone file).

**Comment by liyinan926** [comment]
@prasadnh Move `kafka.pull` out and put it somewhere else. Like what I said above, `gobblin-dist` is intended for system configs only, not for job configs. You can have something like `gobblin-dist/job-conf/kafka.pull`.

**Comment by prasadnh** [comment]
sorry for troubling you guys:)
i removed gobblin-dist and extracted tar. Moved mapreduce property file and started with standalone service with --logdir, I can see logs gobblin-current.log and gc log. but as per this wiki https://github.com/linkedin/gobblin/wiki/Getting%20Started, we need to see job-output file(under workdir) after stopping standalone service. I don't see this file to covert to json using avro.

**Comment by prasadnh** [comment]
Please ignore my previous comment I can see job-output after adding --conf directory and stop the service... but I set workdir is gobblin-dist/bin... can we change job-output location to different location?
I need to look into kafka now...

**Comment by bkotesh** [comment]
hadoop@slave1:~/gobblin/gobblin-dist$ cat nohup.out 
log4j:WARN Failure in post-close rollover action
May 03, 2016 10:31:32 AM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service JobScheduler [FAILED] has failed in the STARTING state.
java.lang.RuntimeException: Found more than one .properties file in directory: /home/hadoop/gobblin/gobblin-dist/conf
	at gobblin.util.SchedulerUtils.loadJobConfigsRecursive(SchedulerUtils.java:192)
	at gobblin.util.SchedulerUtils.loadJobConfigs(SchedulerUtils.java:84)
	at gobblin.scheduler.JobScheduler.loadLocalJobConfigs(JobScheduler.java:377)
	at gobblin.scheduler.JobScheduler.scheduleLocallyConfiguredJobs(JobScheduler.java:366)
	at gobblin.scheduler.JobScheduler.startUp(JobScheduler.java:150)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Thread.java:745)

Exception in thread "JobScheduler STARTING" Exception in thread "main" java.lang.IllegalStateException: Expected to be healthy after starting
	at com.google.common.base.Preconditions.checkState(Preconditions.java:150)
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:278)
	at gobblin.runtime.app.ServiceBasedAppLauncher.start(ServiceBasedAppLauncher.java:144)
	at gobblin.scheduler.SchedulerDaemon.main(SchedulerDaemon.java:63)
java.lang.RuntimeException: Found more than one .properties file in directory: /home/hadoop/gobblin/gobblin-dist/conf
	at gobblin.util.SchedulerUtils.loadJobConfigsRecursive(SchedulerUtils.java:192)
	at gobblin.util.SchedulerUtils.loadJobConfigs(SchedulerUtils.java:84)
	at gobblin.scheduler.JobScheduler.loadLocalJobConfigs(JobScheduler.java:377)
	at gobblin.scheduler.JobScheduler.scheduleLocallyConfiguredJobs(JobScheduler.java:366)
	at gobblin.scheduler.JobScheduler.startUp(JobScheduler.java:150)
	at com.google.common.util.concurrent.AbstractIdleService$2$1.run(AbstractIdleService.java:54)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Thread.java:745)
