### ISSUE TITLE
Caused by: java.util.ConcurrentModificationException writing avro to hdfs

### ISSUE THREAD

**Issue by viacoban** [linkedin/gobblin#476]
extracting avro events from kafka and writing them to avro hdfs gives me this exception every time.
I have a custom implementation of kafka source and extractor. Any idea what could be wrong here?

```
2015-11-23 14:37:19,717 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: Waiting for submitted tasks of job job_EntityUpdate_1448307400669 to complete in container attempt_1447917311755_1914_m_000000_0...
2015-11-23 14:37:19,717 INFO [main] gobblin.runtime.mapreduce.MRJobLauncher: 1 out of 1 tasks of job job_EntityUpdate_1448307400669 are running in container attempt_1447917311755_1914_m_000000_0
2015-11-23 14:37:19,921 INFO [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor: Pulling topic product_update_0
2015-11-23 14:37:19,922 INFO [TaskExecutor-0] gobblin.source.extractor.extract.kafka.KafkaExtractor: Pulling partition product_update_0:0 from offset 4360424 to 4593324, range=232900
2015-11-23 14:37:20,514 ERROR [ForkExecutor-0] gobblin.runtime.Fork-0: Fork 0 of task task_EntityUpdate_1448307400669_0 failed to process data records
org.apache.avro.file.DataFileWriter$AppendWriteException: java.util.ConcurrentModificationException
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:296)
	at gobblin.writer.AvroHdfsDataWriter.write(AvroHdfsDataWriter.java:81)
	at gobblin.writer.AvroHdfsDataWriter.write(AvroHdfsDataWriter.java:46)
	at gobblin.instrumented.writer.InstrumentedDataWriterDecorator.writeImpl(InstrumentedDataWriterDecorator.java:65)
	at gobblin.instrumented.writer.InstrumentedDataWriterBase.write(InstrumentedDataWriterBase.java:122)
	at gobblin.instrumented.writer.InstrumentedDataWriterDecorator.write(InstrumentedDataWriterDecorator.java:58)
	at gobblin.writer.PartitionedDataWriter.write(PartitionedDataWriter.java:108)
	at gobblin.runtime.Fork.processRecords(Fork.java:396)
	at gobblin.runtime.Fork.run(Fork.java:166)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at org.apache.avro.generic.GenericDatumWriter.writeMap(GenericDatumWriter.java:177)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:69)
	at org.apache.avro.generic.GenericDatumWriter.writeField(GenericDatumWriter.java:114)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:104)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:66)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:58)
	at org.apache.avro.file.DataFileWriter.append(DataFileWriter.java:290)
	... 15 more
```

**Comment by liyinan926** [comment]
Have you found what's wrong?

**Comment by viacoban** [comment]
yes, I did, I have implemented a custom avro extractor, and was reusing the GenericRecord instance in extractor. Looks like extractors and writers in gobblin are being executed concurrently.
exception was thrown when same GenericRecord instance was being read into and written from
