### ISSUE TITLE
MRCompactorAvroKeyDedupJobRunner and schema changes

### ISSUE THREAD

**Issue by mwol** [linkedin/gobblin#486]
Input avro schema is set at job level (MRCompactorAvroKeyDedupJobRunner#configureSchema), this should not be the case, as the avro file's own schema will be ignored. e.g. I ran into an error, where I could not even read a file any more, after changing one data type from ["null","string] to ["null","long"] and had mixed input files.
Changes like this are not common and should not occur frequently but anyway, the error should happen when trying to merge files together and not during the reading process, this would give the opportunity to implement some merging/conversion strategy.

```
2015-11-26 17:00:38,924 WARN [main] org.apache.hadoop.mapred.YarnChild: Exception running child : org.apache.avro.AvroTypeException: Found string, expecting union
	at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:292)
	at org.apache.avro.io.parsing.Parser.advance(Parser.java:88)
	at org.apache.avro.io.ResolvingDecoder.readIndex(ResolvingDecoder.java:267)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:155)
	at org.apache.avro.generic.GenericDatumReader.readField(GenericDatumReader.java:193)
	at org.apache.avro.reflect.ReflectDatumReader.readField(ReflectDatumReader.java:230)
	at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:183)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:151)
	at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:142)
	at org.apache.avro.file.DataFileStream.next(DataFileStream.java:233)
	at org.apache.avro.mapreduce.AvroRecordReaderBase.nextKeyValue(AvroRecordReaderBase.java:118)
	at org.apache.avro.mapreduce.AvroKeyRecordReader.nextKeyValue(AvroKeyRecordReader.java:53)
	at gobblin.compaction.mapreduce.avro.AvroKeyCombineFileRecordReader.nextKeyValue(AvroKeyCombineFileRecordReader.java:63)
	at org.apache.hadoop.mapreduce.lib.input.CombineFileRecordReader.nextKeyValue(CombineFileRecordReader.java:69)
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:556)
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:144)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:163)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1671)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:158)
```

**Comment by mwol** [comment]
gobblin.compaction.mapreduce.avro.AvroKeyCombineFileRecordReader#nextKeyValue was overwritten by myself to track the exception...
