### ISSUE TITLE
NoClassDefFoundError: gobblin/util/JobConfigurationUtils

### ISSUE THREAD

**Issue by x10ba** [linkedin/gobblin#510]
Sys: centos
hdp: 2.7.1

invoke:
./gobblin-mapreduce.sh --conf ~/gobblin/gobblin-dist/conf/gobblin-mapreduce.properties  --workdir ~/gobblin/work --jars ~/gobblin/gobblin-dist/lib/gobblin-utility.jar

returns this error:
WARNING: Use "yarn jar" to launch YARN applications.
Exception in thread "main" java.lang.NoClassDefFoundError: gobblin/util/JobConfigurationUtils
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:56)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: gobblin.util.JobConfigurationUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

**Comment by liyinan926** [comment]
First of all, the option `--conf` is for job configuration file like `.job` or `.pull` files, not for system configuration file like `gobblin-mapreduce.properties`, which gets loaded automatically so you don't need to. Second, `--jars` is for additional jars not included in `lib/` you need to run your job.

**Comment by x10ba** [comment]
Hi,
Well. 

[x10ba]$ ./gobblin-mapreduce.sh --conf ~/gobblin/gobblin-dist/conf/mp1.job  --workdir ~/gobblin/work

WARNING: Use "yarn jar" to launch YARN applications.
Exception in thread "main" java.lang.NoClassDefFoundError: gobblin/util/JobConfigurationUtils
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:56)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.lang.ClassNotFoundException: gobblin.util.JobConfigurationUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 9 more

**Comment by liyinan926** [comment]
Are you running this based off the uncompressed targ ball `gobblin-dist.tar.gz`?

**Comment by x10ba** [comment]
Yes. and versioned on 2.7.1

**Comment by liyinan926** [comment]
Can you check if you have `gobblin-utility.jar` under `lib/`?

**Comment by x10ba** [comment]
Hi.
Yes. gobblin-utility.jar is in lib/
Thanks,
x10ba

**Comment by sahilTakiar** [comment]
@x10ba did you get this working?

**Comment by x10ba** [comment]
Hi,
I re-compiled gobblin from source, but I get this error now:

Mac os
// run this
./gobblin-standalone.sh start

// get this error
Error: Environment variable JAVA_HOME not set!

// my JAVA_HOME is set in .bash_profile and via Environment Variables plugin

**Comment by sahilTakiar** [comment]
@x10ba you need to make sure `JAVA_HOME` is set properly.
