### ISSUE TITLE
Published gobblin-rest-api jar contains no code

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#545]
The published gobblin-rest-api jar (http://search.maven.org/remotecontent?filepath=com/linkedin/gobblin/gobblin-rest-api/0.6.0/gobblin-rest-api-0.6.0.jar) contains no code.  This library is only ~260 bytes, but the expected size should be ~40 kilobytes.  The gobblin-rest-api project produces multiple jars, one that is the output of the project and the other that is the output of rest.li (pegasus).  I saw a similar issue when building PR #544.  The solution was to change the gobblin-rest-api build.gradle to disable publishing of the default jar and publish the data-template jar instead.

**Comment by kadaan** [comment]
@liyinan926 @chavdar This issue makes it impossible to build/run based on the maven libraries.

This is the error that occurs when trying to run with the latest libraries:
```
Caused by: java.lang.NoClassDefFoundError: gobblin/rest/LauncherTypeEnum
	at gobblin.runtime.JobState.getLauncherType(JobState.java:325)
	at gobblin.runtime.JobExecutionEventSubmitter.submitJobStateEvent(JobExecutionEventSubmitter.java:71)
	at gobblin.runtime.JobExecutionEventSubmitter.submitJobExecutionEvents(JobExecutionEventSubmitter.java:54)
	at gobblin.runtime.JobExecutionEventSubmitterListener.onJobCompletion(JobExecutionEventSubmitterListener.java:18)
	at gobblin.runtime.JobListeners$ParallelJobListener$1.call(JobListeners.java:68)
	at gobblin.runtime.JobListeners$ParallelJobListener$1.call(JobListeners.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
```

## gobblin-rest-api comparison ##
### Version: 0.5.0 ###
<img width="813" alt="screen shot 2015-12-18 at 1 59 17 pm" src="https://cloud.githubusercontent.com/assets/1904898/11908315/dd9f20a0-a58f-11e5-8eb0-f1173aa20d59.png">

### Version: 0.6.0 ###
<img width="808" alt="screen shot 2015-12-18 at 1 59 04 pm" src="https://cloud.githubusercontent.com/assets/1904898/11908312/d6c140a6-a58f-11e5-92d6-a5fb72761bb9.png">

**Comment by kadaan** [comment]
Fixed by #550

**Comment by kadaan** [comment]
#550 is an incomplete fix.

**Comment by kadaan** [comment]
@chavdar What is the status of the rest.li fix?

**Comment by kadaan** [comment]
I believe this is now fixed

**Comment by kadaan** [comment]
@chavdar Can you explain why you did this: https://github.com/linkedin/gobblin/commit/652e5a304239ce62bb7f494f6ab2d03ec5d1f510  Wouldn't it just be better to stop producing the empty jar?

**Comment by sahilTakiar** [comment]
Is this still an issue?

**Comment by kadaan** [comment]
I think this is fixed now.
