### ISSUE TITLE
Gobblin Problem No AbstractFileSystem for scheme: null

### ISSUE THREAD

**Issue by vamsilingala** [linkedin/gobblin#577]
Hi,

Good Day!

hadoop version
Hadoop 2.5.0-cdh5.3.3

I am getting below exception when I run below shell script. Please suggest me the solution.

bin/gobblin-mapreduce.sh --conf /home/nagendras/DataIngestion/gobblin-master/gobblin-dist/jobconf/kafkatoHDFSMapR.pull

ERROR [AbstractJobLauncher] Failed to launch and run job job_GobblinKafkaQuickStart_1451372191797: org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: null
org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: null
        at org.apache.hadoop.fs.AbstractFileSystem.createFileSystem(AbstractFileSystem.java:153)
        at org.apache.hadoop.fs.AbstractFileSystem.get(AbstractFileSystem.java:241)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:333)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:330)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
        at org.apache.hadoop.fs.FileContext.getAbstractFileSystem(FileContext.java:330)
        at org.apache.hadoop.fs.FileContext.getFileContext(FileContext.java:444)
        at org.apache.hadoop.mapred.YARNRunner.createApplicationSubmissionContext(YARNRunner.java:359)
        at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:284)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1614)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
        at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:186)
        at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:249)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:60)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:133)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Failed to launch the job due to the following exception:
gobblin.runtime.JobException: Job job_GobblinKafkaQuickStart_1451372191797 failed

my job.pull

job.name=GobblinKafkaQuickStart
job.group=GobblinKafka
job.description=Gobblin quick start job for Kafka
job.lock.enabled=false

kafka.brokers=localhost:9092

source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=txt

data.publisher.type=gobblin.publisher.BaseDataPublisher

mr.job.max.mappers=1

metrics.reporting.file.enabled=true
metrics.log.dir=/gobblin-kafka/metrics
metrics.reporting.file.suffix=txt

bootstrap.with.offset=earliest

fs.uri=hdfs://INMBZP4099.in.dst.iit.com:8020
writer.fs.uri=hdfs://INMBZP4099.in.dst.iit.com:8020
state.store.fs.uri=hdfs://INMBZP4099.in.dst.iit.com:8020

mr.job.root.dir=/gobblin-kafka/working
state.store.dir=/gobblin-kafka/state-store
task.data.root.dir=/jobs/kafkaetl/gobblin/gobblin-kafka/task-data
data.publisher.final.dir=/gobblintest/job-output

I could able to list the files in cmd using hdfs://INMBZP4099.in.dst.iit.com:8020
example hadoop fs -ls hdfs://INMBZP4099.in.dst.iit.com:8020

Thanks in advance!

Regards,
Vamsi.

**Comment by vamsilingala** [comment]
Please someone respond....

**Comment by vamsilingala** [comment]
Problem is fixed..
Thanks to Sahil Takiar for updating wiki

https://github.com/linkedin/gobblin/wiki/FAQs#how-do-i-fix-unsupportedfilesystemexception-no-abstractfilesystem-for-scheme-null
