### ISSUE TITLE
Something wrong when  gobblin runing for  dump kafka to hdfs.   There is the  ERROR .

### ISSUE THREAD

**Issue by superwood** [linkedin/gobblin#614]
build cmd
    ./gradlew clean build -PuseHadoop2  -PhadoopVersion=2.3.0-cdh5.1.0

ERROR [AbstractJobLauncher] Failed to launch and run job job_KafkaExampleJob_1453187284612: java.lang.AbstractMethodError
java.lang.AbstractMethodError
	at org.apache.hadoop.io.retry.RetryInvocationHandler.<init>(RetryInvocationHandler.java:73)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.<init>(RetryInvocationHandler.java:64)
	at org.apache.hadoop.io.retry.RetryProxy.create(RetryProxy.java:58)
	at org.apache.hadoop.yarn.client.RMProxy.createRMProxy(RMProxy.java:95)
	at org.apache.hadoop.yarn.client.ClientRMProxy.createRMProxy(ClientRMProxy.java:72)
	at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.serviceStart(YarnClientImpl.java:113)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at org.apache.hadoop.mapred.ResourceMgrDelegate.serviceStart(ResourceMgrDelegate.java:108)
	at org.apache.hadoop.service.AbstractService.start(AbstractService.java:193)
	at org.apache.hadoop.mapred.ResourceMgrDelegate.<init>(ResourceMgrDelegate.java:97)
	at org.apache.hadoop.mapred.YARNRunner.<init>(YARNRunner.java:112)
	at org.apache.hadoop.mapred.YarnClientProtocolProvider.create(YarnClientProtocolProvider.java:34)
	at org.apache.hadoop.mapreduce.Cluster.initialize(Cluster.java:95)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:82)
	at org.apache.hadoop.mapreduce.Cluster.<init>(Cluster.java:75)
	at org.apache.hadoop.mapreduce.Job$9.run(Job.java:1255)
	at org.apache.hadoop.mapreduce.Job$9.run(Job.java:1251)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapreduce.Job.connect(Job.java:1250)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1279)
	at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:198)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:245)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:60)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)

**Comment by ibuenros** [comment]
Can you include your job configuration?

**Comment by superwood** [comment]
I  fixed this problem。 In the  gobblin-mapreducer.sh  ,jars  include by var  "LIBJARS" is wrong.
