### ISSUE TITLE
Gobblin Build Failed - FileAwareInputStreamDataWriterTest : testCommit 

### ISSUE THREAD

**Issue by bjvanov** [linkedin/gobblin#656]
Attempt to build gobblin according to the README using the following command:

> ./gradlew clean build -PuseHadoop2 -PhadoopVersion=2.7.1

yields failure of **testCommit** test from **FileAwareInputStreamDataWriterTest**. The build report suggests that the build is trying to edit the permissions of a group that does not exists:

> ExitCodeException exitCode=1: chown: SANDIA\Domain: illegal group name

**Comment by sahilTakiar** [comment]
Trying building with `-x test` at the end of your command, that will prevent any tests from running.

**Comment by bjvanov** [comment]
This gave me a successful build. Thank you.

**Comment by chavdar** [comment]
@bjvanov do you still have the exact exception stack trace. That is a strange exception as the code uses permissions from the existing file system. Are you by any chance running on a SMB-mounted path?

**Comment by krtiwari1981** [comment]
Same issue here, I attempted to build after cloning using below command and it failed. Build is successful after -x test

./gradlew clean build -PuseHadoop2

Error ----
org.apache.hadoop.util.Shell$ExitCodeException: chown: CORP\Domain: illegal group name

	at org.apache.hadoop.util.Shell.runCommand(Shell.java:505)
	at org.apache.hadoop.util.Shell.run(Shell.java:418)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:650)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:739)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:722)
	at org.apache.hadoop.fs.FileUtil.execCommand(FileUtil.java:1097)
	at org.apache.hadoop.fs.FileUtil.setOwner(FileUtil.java:899)
	at org.apache.hadoop.fs.RawLocalFileSystem.setOwner(RawLocalFileSystem.java:617)
	at org.apache.hadoop.fs.FilterFileSystem.setOwner(FilterFileSystem.java:456)
	at gobblin.data.management.copy.writer.FileAwareInputStreamDataWriter.ensureDirectoryExists(FileAwareInputStreamDataWriter.java:338)
	at gobblin.data.management.copy.writer.FileAwareInputStreamDataWriter.commit(FileAwareInputStreamDataWriter.java:291)
	at gobblin.data.management.copy.writer.FileAwareInputStreamDataWriterTest.testCommit(FileAwareInputStreamDataWriterTest.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:112)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
