### ISSUE TITLE
mapreduce version failing 

### ISSUE THREAD

**Issue by saggidarren** [linkedin/gobblin#672]
The error is as shown: 
```
WARNING: Use "yarn jar" to launch YARN applications.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/gobblin-dist/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.4.0-3485/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2016-02-06 03:00:22 UTC ERROR [main] gobblin.runtime.mapreduce.CliMRJobLauncher  52 - Failed to launch the job!
gobblin.runtime.JobException: Job job_PullFromKafkaAvro_1454727620905 failed
        at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:320)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:50)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
```
The config file looks like: 
```
job.name=PullFromKafkaAvro
job.group=GobblinKafkaAvro
job.description=Kafka Extractor for Gobblin to Avro
job.lock.enabled=false
# source config
kafka.brokers=\<brokermachine:9092\>

# source class
source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource



extract.namespace=gobblin.extract.kafka

writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename

writer.destination.type=HDFS
writer.output.format=AVRO


data.publisher.type=gobblin.publisher.BaseDataPublisher

topic.whitelist=<eventname>
bootstrap.with.offset=latest

metrics.reporting.file.enabled=true
metrics.log.dir=${env:GOBBLIN_WORK_DIR}/metrics
metrics.reporting.file.suffix=txt
fs.uri=hdfs:\<hostname\>/
writer.fs.uri=hdfs:/<hostname>/
state.store.fs.uri=hdfs:/<hostname>/
mr.job.root.dir=/user/gobblin/gobblin-kafka/working
state.store.dir=/user/gobblin/gobblin-kafka/state-store
task.data.root.dir=/user/gobblin/gobblin/gobblin-kafka/task-data
data.publisher.final.dir=/data/tracking
```

**Comment by chavdar** [comment]
Are there more logs? It is not clear from the above log what the actual
error is.

**Comment by saggidarren** [comment]
Hello Chavdar,

I am using hortonworks version of hadoop-2.3.4. 
I can say that the problem is around these values:
```
fs.uri=hdfs:\<hostname\>/
writer.fs.uri=hdfs:/<hostname>/
state.store.fs.uri=hdfs:/<hostname>/
```
I think i need to find out what is the correct fs.uri as I see the following in the log file:
```
2016-02-06 17:41:28 UTC INFO  [main] org.apache.hadoop.mapreduce.lib.input.FileInputFormat  287 - Total input paths to process : 1
2016-02-06 17:41:28 UTC INFO  [main] org.apache.hadoop.mapreduce.JobSubmitter  396 - number of splits:100
2016-02-06 17:41:28 UTC INFO  [main] org.apache.hadoop.mapreduce.JobSubmitter  479 - Submitting tokens for job: job_1454555634209_0025
2016-02-06 17:41:28 UTC WARN  [main] org.apache.hadoop.security.UserGroupInformation  1551 - PriviledgedActionException as:gobblin (auth:SIMPLE) cause:org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: null
2016-02-06 17:41:28 UTC INFO  [main] org.apache.hadoop.mapreduce.JobSubmitter  441 - Cleaning up the staging area /user/gobblin/.staging/job_1454555634209_0025
2016-02-06 17:41:28 UTC WARN  [main] org.apache.hadoop.security.UserGroupInformation  1551 - PriviledgedActionException as:gobblin (auth:SIMPLE) cause:org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: null
2016-02-06 17:41:28 UTC INFO  [TaskStateCollectorService STOPPING] gobblin.runtime.TaskStateCollectorService  100 - Stopping the TaskStateCollectorService
2016-02-06 17:41:28 UTC WARN  [TaskStateCollectorService STOPPING] gobblin.runtime.TaskStateCollectorService  122 - Output task state path /user/gobblin/gobblin-kafka/working/PullFromKafkaAvro/output/job_PullFromKafkaAvro_1454780486318 does not exist
2016-02-06 17:41:28 UTC INFO  [main] gobblin.runtime.mapreduce.MRJobLauncher  443 - Deleted working directory /user/gobblin/gobblin-kafka/working/PullFromKafkaAvro
2016-02-06 17:41:28 UTC ERROR [main] gobblin.runtime.AbstractJobLauncher  280 - Failed to launch and run job job_PullFromKafkaAvro_1454780486318: org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: null
org.apache.hadoop.fs.UnsupportedFileSystemException: No AbstractFileSystem for scheme: null
        at org.apache.hadoop.fs.AbstractFileSystem.createFileSystem(AbstractFileSystem.java:152)
        at org.apache.hadoop.fs.AbstractFileSystem.get(AbstractFileSystem.java:240)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:332)
        at org.apache.hadoop.fs.FileContext$2.run(FileContext.java:329)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.fs.FileContext.getAbstractFileSystem(FileContext.java:329)
        at org.apache.hadoop.fs.FileContext.getFileContext(FileContext.java:443)
        at org.apache.hadoop.mapred.YARNRunner.createApplicationSubmissionContext(YARNRunner.java:360)
        at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:285)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:432)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
        at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:200)
        at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:261)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:50)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:77)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
```

Let me know if I am checking in the right direction?

**Comment by sahilTakiar** [comment]
Check out this entry in the FAQ: https://github.com/linkedin/gobblin/wiki/FAQs#how-do-i-fix-unsupportedfilesystemexception-no-abstractfilesystem-for-scheme-null

**Comment by saggidarren** [comment]
Thanks Sahil

**Comment by saggidarren** [comment]
Hello Folks
I am getting another error which is as follows:

I added the jars in gobblin-mapreduce.sh:
```
export HORTON_JARS="/usr/hdp/2.3.4.0-3485/hadoop-hdfs/lib:/usr/hdp/2.3.4.0-3485/hadoop/lib:/usr/hdp/2.3.4.0-3485/hadoop-mapreduce/lib:/usr/hdp/2.3.4.0-3485/hadoop-yarn/lib:/usr/hdp/2.3.4.0-3485/hbase/lib:/usr/hdp/2.3.4.0-3485/phoenix/lib"
export HADOOP_CLASSPATH=$GOBBLIN_DEP_JARS:$HADOOP_CLASSPATH:$HADOOP_JARS
```
Error seems to point to Play framework 
```
2016-02-09 18:56:27,658 INFO [TaskExecutor STARTING] gobblin.runtime.TaskExecutor: Starting the task executor
2016-02-09 18:56:27,658 INFO [MRTaskStateTracker STARTING] gobblin.runtime.mapreduce.MRTaskStateTracker: Starting the task state tracker
2016-02-09 18:56:27,685 INFO [main] gobblin.metrics.GobblinMetrics: Not reporting metrics to JMX
2016-02-09 18:56:27,705 WARN [main] org.apache.hadoop.hdfs.ClientContext: Existing client context 'default' does not match requested configuration.  Existing: shortCircuitStreamsCacheSize = 4096, shortCircuitStreamsCacheExpiryMs = 300000, shortCircuitMmapCacheSize = 256, shortCircuitMmapCacheExpiryMs = 3600000, shortCircuitMmapCacheRetryTimeout = 300000, shortCircuitCacheStaleThresholdMs = 1800000, socketCacheCapacity = 16, socketCacheExpiry = 3000, shortCircuitLocalReads = true, useLegacyBlockReaderLocal = false, domainSocketDataTraffic = false, shortCircuitSharedMemoryWatcherInterruptCheckMs = 60000, keyProviderCacheExpiryMs = 864000000, Requested: shortCircuitStreamsCacheSize = 256, shortCircuitStreamsCacheExpiryMs = 300000, shortCircuitMmapCacheSize = 256, shortCircuitMmapCacheExpiryMs = 3600000, shortCircuitMmapCacheRetryTimeout = 300000, shortCircuitCacheStaleThresholdMs = 1800000, socketCacheCapacity = 16, socketCacheExpiry = 3000, shortCircuitLocalReads = false, useLegacyBlockReaderLocal = false, domainSocketDataTraffic = false, shortCircuitSharedMemoryWatcherInterruptCheckMs = 60000, keyProviderCacheExpiryMs = 864000000
2016-02-09 18:56:27,739 FATAL [main] org.apache.hadoop.mapred.YarnChild: Error running child : java.lang.NoClassDefFoundError: com/typesafe/config/ConfigFactory
	at gobblin.util.ConfigUtils.propertiesToConfig(ConfigUtils.java:95)
	at gobblin.metrics.reporter.OutputStreamReporter$Builder.build(OutputStreamReporter.java:162)
	at gobblin.metrics.GobblinMetrics.buildFileMetricReporter(GobblinMetrics.java:468)
	at gobblin.metrics.GobblinMetrics.startMetricReporting(GobblinMetrics.java:380)
	at gobblin.metrics.GobblinMetrics.startMetricReportingWithFileSuffix(GobblinMetrics.java:340)
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.setup(MRJobLauncher.java:533)
	at gobblin.runtime.mapreduce.MRJobLauncher$TaskRunner.run(MRJobLauncher.java:540)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: java.lang.ClassNotFoundException: com.typesafe.config.ConfigFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.jar
```

**Comment by ibuenros** [comment]
Hi Dhawal,
You need to have Typesafe config artifacts in the classpath:
http://search.maven.org/#artifactdetails%7Ccom.typesafe%7Cconfig%7C1.3.0%7Cbundle

Hope this helps.
Issac

**Comment by sahilTakiar** [comment]
This issue was fixed in https://github.com/linkedin/gobblin/pull/690 which I just merged.

**Comment by sahilTakiar** [comment]
Marking as resolved, let me know if there are still issues.
