### ISSUE TITLE
Fix intermittently failing tests

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#709]
Some tests fail intermittently which cause unreliable travis builds.  These tests should be fixed.  Below is a list of all intermittently failing tests:

```
Formatting ./build/gobblin-yarn/test-results/TEST-gobblin.yarn.GobblinApplicationMasterTest.xml
=====================================================
Testsuite: gobblin.yarn.GobblinApplicationMasterTest
Tests run: 2, Failures: 1, Errors: 0, Time elapsed: 54.622 sec
--------- ----------- ---------
Testcase: testSendShutdownRequest took 31.888 FAILURE
 java.util.concurrent.TimeoutException: Timeout waiting for condition '1 message queued'. java.util.concurrent.TimeoutException
java.util.concurrent.TimeoutException: Timeout waiting for condition '1 message queued'.
    at gobblin.testing.AssertWithBackoff.assertTrue(AssertWithBackoff.java:185)
    at gobblin.testing.AssertWithBackoff.assertTrue(AssertWithBackoff.java:134)
    at gobblin.testing.AssertWithBackoff.assertEquals(AssertWithBackoff.java:147)
    at gobblin.yarn.GobblinApplicationMasterTest.testSendShutdownRequest(GobblinApplicationMasterTest.java:135)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
    at org.testng.TestRunner.privateRun(TestRunner.java:773)
    at org.testng.TestRunner.run(TestRunner.java:623)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
    at org.testng.SuiteRunner.run(SuiteRunner.java:259)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
    at org.testng.TestNG.run(TestNG.java:1018)
    at org.gradle.api.internal.tasks.testing.testng.TestNGTestClassProcessor.stop(TestNGTestClassProcessor.java:112)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:57)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
    at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
    at com.sun.proxy.$Proxy2.stop(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:115)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
    at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.messaging.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:355)
    at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Testcase: testHandleApplicationMasterShutdownRequest took 0.0 SUCCESS
------ Standard output ------
------ Error output ------
=====================================================
```

NOTE: The above result is from a Travis build for #705 which includes the failing tests at the end of the build log.

**Comment by sahilTakiar** [comment]
I would be nice if we could see the stability of each individual test. How frequently does it fail? How many times has in failed in the last 10 builds? etc.

Seems Jenkins has a plugin like this: https://wiki.jenkins-ci.org/display/JENKINS/Test+stability+plugin

Couldn't find anything similar for GitHub or Travis.

**Comment by kadaan** [comment]
Wonder if something like http://junitth.sourceforge.net would work?

**Comment by abti** [comment]
It was fixed by @htran1
