### ISSUE TITLE
Pulling data from Kafka in mapreduce mode failed

### ISSUE THREAD

**Issue by hegu8** [linkedin/gobblin#738]
My Gobblin version is 0.6.2, built with hadoop 2.6.0.

I was trying to pull data from Kafka using the settings in the Kafka HDFS Ingestion tutorial, but I got some error:
```
2016-02-22 15:30:12,822 ERROR [ForkExecutor-0] gobblin.runtime.Fork-0: Fork 0 of task task_PullCampaignTraffic_1456183695112_7 failed to process data records
java.lang.IllegalArgumentException: java.net.URISyntaxException: Relative path in absolute URI: ${env:GOBBLIN_WORK_DIR%7D/task-staging
	at org.apache.hadoop.fs.Path.initialize(Path.java:206)
	at org.apache.hadoop.fs.Path.<init>(Path.java:172)
	at org.apache.hadoop.fs.Path.<init>(Path.java:99)
	at gobblin.util.WriterUtils.getWriterStagingDir(WriterUtils.java:67)
	at gobblin.writer.FsDataWriter.<init>(FsDataWriter.java:85)
	at gobblin.writer.SimpleDataWriter.<init>(SimpleDataWriter.java:56)
	at gobblin.writer.SimpleDataWriterBuilder.build(SimpleDataWriterBuilder.java:32)
	at gobblin.writer.PartitionedDataWriter.<init>(PartitionedDataWriter.java:94)
	at gobblin.runtime.Fork.buildWriter(Fork.java:369)
	at gobblin.runtime.Fork.buildWriterIfNotPresent(Fork.java:375)
	at gobblin.runtime.Fork.processRecords(Fork.java:395)
	at gobblin.runtime.Fork.run(Fork.java:168)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.URISyntaxException: Relative path in absolute URI: ${env:GOBBLIN_WORK_DIR%7D/task-staging
	at java.net.URI.checkPath(URI.java:1823)
	at java.net.URI.<init>(URI.java:745)
	at org.apache.hadoop.fs.Path.initialize(Path.java:203)
	... 18 more
```
Has anyone seen this before?

**Comment by kadaan** [comment]
What is the value of the `GOBBLIN_WORK_DIR` environment variable?

**Comment by hegu8** [comment]
It's /home/hegu/tmp/gobblin-hadoop-2.6.0/work, still having the same issue after removing the dashes and dots

**Comment by kadaan** [comment]
When I run standalone, I configure the `fs.uri=file:///` and `${env:GOBBLIN_WORK_DIR}=work/gobblin`.  For running in Yarn I use: `fs.uri="hdfs://SERVER.compute-1.amazonaws.com:9000"` and `writer.staging.dir=/work/gobblin/SCHEMA/task-staging`.

What is the value of your `fs.uri`?

**Comment by hegu8** [comment]
I overwrite `writer.staging.dir` to point to a dir in hdfs and it worked, thank you so much!
