### ISSUE TITLE
Running gobblin on mapreduce mode ..error

### ISSUE THREAD

**Issue by krtiwari1981** [linkedin/gobblin#779]
Below is the command i used to run

./gobblin-mapreduce.sh --conf /home/ec2-user/in/wikipedia.pull

below is the error 

./gobblin-mapreduce.sh --conf /home/ec2-user/in/wikipedia.pull
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ec2-user/gobblin-dist/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/lib/qubole/packages/hadoop2/hadoop2/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2016-03-01 09:47:37 UTC ERROR [main] gobblin.runtime.mapreduce.CliMRJobLauncher  52 - Failed to launch the job!
gobblin.runtime.JobException: Job job_GobblinKafkaQuickStart_1456825653538 failed
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:356)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:50)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

Can you help?

The log file has below error

2016-03-01 09:47:36 UTC INFO  [main] gobblin.runtime.mapreduce.MRJobLauncher  443 - Deleted working directory gobblin-kafka/working/GobblinKafkaQuickStart
2016-03-01 09:47:36 UTC ERROR [main] gobblin.runtime.AbstractJobLauncher  307 - Failed to launch and run job job_GobblinKafkaQuickStart_1456825653538: java.lang.NoSuchMethodError: org.apache.hadoop.net.NetUtils.createSocketAddr(Lorg/apache/hadoop/conf/Configuration;Ljava/lang/String;)Ljava/net/InetSocketAddress;
java.lang.NoSuchMethodError: org.apache.hadoop.net.NetUtils.createSocketAddr(Lorg/apache/hadoop/conf/Configuration;Ljava/lang/String;)Ljava/net/InetSocketAddress;
        at org.apache.hadoop.mapred.ClientCache$1.run(ClientCache.java:95)
        at org.apache.hadoop.mapred.ClientCache$1.run(ClientCache.java:92)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:356)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1608)
        at org.apache.hadoop.mapred.ClientCache.instantiateHistoryProxy(ClientCache.java:92)
        at org.apache.hadoop.mapred.ClientCache.getInitializedHSProxy(ClientCache.java:77)
        at org.apache.hadoop.mapred.YARNRunner.addHistoryToken(YARNRunner.java:185)
        at org.apache.hadoop.mapred.YARNRunner.submitJob(YARNRunner.java:282)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:536)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1296)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1293)
        at java.security.AccessController.doPrivileged(Native Method)

**Comment by kadaan** [comment]
Most times `java.lang.NoSuchMethodError: org.apache.hadoop.net.NetUtils.createSocketAddr(Lorg/apache/hadoop/conf/Configuration;Ljava/lang/String;)Ljava/net/InetSocketAddress;` means there is a mismatch between what jars gobblin is expecting and the jars in the classpath.  Can you figure out what versions on hadoop-common is in your classpath?  Also, I wasn't able to find any version/flavor of hadoop where `NetUtils.createSocketAddr` has a `Configuration` as the first parameter.

**Comment by krtiwari1981** [comment]
The version is hadoop-yarn-server-common-2.6.0-qds-0.4.0-SNAPSHOT.jar and hadoop-yarn-common-2.6.0-qds-0.4.0-SNAPSHOT.jar.

Also before this i had encountered the issue 
Exception in thread "main" java.io.FileNotFoundException: File /home/ec2-user/gobblin-dist/lib/gson-2.3.1.jar does not exist.

and 

Exception in thread "main" java.io.FileNotFoundException: File /home/ec2-user/gobblin-dist/lib/joda-time-2.9.jar does not exist

I moved ahead by 

mv ~/gobblin-dist/lib/gson-2.6.1.jar ~/gobblin-dist/lib/gson-2.3.1.jar
mv ~/gobblin-dist/lib/joda-time-2.9.2.jar ~/gobblin-dist/lib/joda-time-2.9.jar 

but untill i had the above issue is comment # 1

**Comment by kadaan** [comment]
This is definitely a classpath issue. Qubole has modified their version of the Hadoop libraries and you will be bitten unless you make sure they are first in the class path.

**Comment by krtiwari1981** [comment]
This is fixed after changes in class path

**Comment by kadaan** [comment]
@krtiwari1981 Can you please explain what the specific changes were to assist anyone else trying to run on qubole?

**Comment by krtiwari1981** [comment]
The issue is resolved by putting hadoop-common-2.6.0-qds-0.4.0-SNAPSHOT.jar in lib directory of gobblin.
