### ISSUE TITLE
Fork not working 

### ISSUE THREAD

**Issue by krtiwari1981** [linkedin/gobblin#782]
I am trying to enable fork but it doesn't seem to work for me. Below is the change i did in pull file. If i remove these changes everything works. Any idea, am i missing something?

fork.branches=2

writer.fs.uri.0=hdfs:/hostname:9000
writer.destination.type.0=HDFS
writer.output.format.0=txt
writer.staging.dir.0=gobblin/example/task-staging/purged
writer.output.dir.0=gobblin/example/task-output/purged
data.publisher.final.dir.0=gobblin/example/job-output/purged

writer.fs.uri.1=hdfs://hostname:9000
writer.destination.type.1=HDFS
writer.output.format.1=txt
writer.staging.dir.1=gobblin/example/task-staging/normal
writer.output.dir.1=gobblin/example/task-output/normal
data.publisher.final.dir.1=gobblin/example/job-output/normal

Errror : --

2016-03-02 01:58:04 UTC ERROR [main] gobblin.runtime.mapreduce.CliMRJobLauncher  52 - Failed to launch the job!
gobblin.runtime.JobException: Job job_GobblinKafkaQuickStart_1456883850373 failed
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:356)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:50)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:223)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

**Comment by sahilTakiar** [comment]
Being discussed in: https://groups.google.com/d/topic/gobblin-users/1ig4_weF_HY/discussion
