### ISSUE TITLE
Missing jars at job launch

### ISSUE THREAD

**Issue by estol** [linkedin/gobblin#787]
Hi,

whenever I try to launch a Gobblin job I get the following error message:

WARNING: Use "yarn jar" to launch YARN applications.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/whatever/Product/gobblin/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/hdp/2.3.2.0-2950/hadoop/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.io.FileNotFoundException: File /usr/whatever/Product/gobblin/lib/gson-2.3.1.jar does not exist.
        at org.apache.hadoop.util.GenericOptionsParser.validateFiles(GenericOptionsParser.java:405)
        at org.apache.hadoop.util.GenericOptionsParser.processGeneralOptions(GenericOptionsParser.java:300)
        at org.apache.hadoop.util.GenericOptionsParser.parseGeneralOptions(GenericOptionsParser.java:487)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:170)
        at org.apache.hadoop.util.GenericOptionsParser.<init>(GenericOptionsParser.java:153)
        at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

The gson artifact is present in the lib directory, but a higher version number. If I symlink it, different artifacts throw similar errors.

Previous version was okay.
Currently on branch master at revision:
c5cad0142c7ad7e9127dea6b49892980afb7a61f

Previous revision was 779fa89 on branch master.

**Comment by sahilTakiar** [comment]
Are you using `bin/gobblin-mapreduce.sh`? If so you need to manually modify the script, specifically line 143 where `gson-2.3.1` is specified.

We have an Issue open about fixing this: https://github.com/linkedin/gobblin/issues/693

**Comment by estol** [comment]
Yes, it is running with the gobblin-mapreduce.sh.

Will try it.

Thanks for the help (-:

**Comment by sahilTakiar** [comment]
@estol did this end up working for you?
