### ISSUE TITLE
issue with new gobblin build

### ISSUE THREAD

**Issue by madhukotagiri** [linkedin/gobblin#810]
Hi Iam working on gobblin .
previously the gobblin which is installed in my machine was worked fine ..with configuration file.
recently we downloaded the new source and builded the code but we are facing below errror.

org.apache.hadoop.ipc.RemoteException: Server IPC version 9 cannot communicate with client version 4
	at org.apache.hadoop.ipc.Client.call(Client.java:1113)
	at org.apache.hadoop.ipc.RPC$Invoker.invoke(RPC.java:229)
	at com.sun.proxy.$Proxy6.getProtocolVersion(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:85)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:62)
	at com.sun.proxy.$Proxy6.getProtocolVersion(Unknown Source)
	at org.apache.hadoop.ipc.RPC.checkVersion(RPC.java:422)
	at org.apache.hadoop.hdfs.DFSClient.createNamenode(DFSClient.java:183)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:281)
	at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:245)
	at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:100)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:1446)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:67)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:1464)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:263)
	at gobblin.util.WriterUtils.getWriterFS(WriterUtils.java:269)
	at gobblin.qualitychecker.row.RowLevelPolicyCheckerBuilder.build(RowLevelPolicyCheckerBuilder.java:82)
	at gobblin.runtime.TaskContext.getRowLevelPolicyChecker(TaskContext.java:256)
	at gobblin.runtime.Fork.<init>(Fork.java:128)
	at gobblin.runtime.Task.run(Task.java:156)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by zliu41** [comment]
Seems the Hadoop version you are building with is different from the version.
Have you tried using option `-PhadoopVersion=[your-hadoop-version]` for build?

**Comment by madhukotagiri** [comment]
please refer the below issue.
https://github.com/linkedin/gobblin/issues/786
iam did same as per the above issue.
but facing mentioned isse in this current issue 810

**Comment by madhukotagiri** [comment]
please let me know the status of this?

**Comment by sahilTakiar** [comment]
So are you blocked on this Issue or on #786?

The resolution for #786 is to run `gradlew clean assemble -Pversion=gobblin_0.6.2-180-g5a11598`

The resolution to this issue would just be to add `-PhadoopVersion=[your-hadoop-version]` to the build command.

So the final command would look like: `gradlew clean assemble -Pversion=gobblin_0.6.2-180-g5a11598 -PhadoopVersion=[your-hadoop-version]`

**Comment by madhukotagiri** [comment]
I tried with as u mentioned above command but facing the issue:


FAILURE: Build failed with an exception.

* Where:
Build file '/opt/buildgobblin/gobblin-master/gobblin-compaction/build.gradle' line: 57

* What went wrong:
A problem occurred evaluating project ':gobblin-compaction'.
> Could not resolve all dependencies for configuration ':gobblin-compaction:runtime'.
   > Could not find org.apache.hadoop:hadoop-core:2.6.0.
     Required by:
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-api:gobblin_0.6.2-180-g5a11598
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-utility:gobblin_0.6.2-180-g5a11598
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-metrics:gobblin_0.6.2-180-g5a11598
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-core:gobblin_0.6.2-180-g5a11598
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-core:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-tunnel:gobblin_0.6.2-180-g5a11598
         com.linkedin.gobblin:gobblin-compaction:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-core:gobblin_0.6.2-180-g5a11598 > com.linkedin.gobblin:gobblin-hive-registration:gobblin_0.6.2-180-g5a11598

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by ibuenros** [comment]
Can you try
gradlew clean assemble -Pversion=gobblin_0.6.2-180-g5a11598 -PuseHadoop2
-PhadoopVersion=[your-hadoop-version]

**Comment by sahilTakiar** [comment]
@madhukotagiri did you get this working?
