### ISSUE TITLE
gobblin-mapreduce fails due to NullpointerException of JobConfigurationUtils.putPropertiesIntoConfiguration

### ISSUE THREAD

**Issue by liuxuan207** [linkedin/gobblin#864]
- hdp:2.6.0

bin/gobblin-mapreduce.sh --conf job.job

Exception in thread "main" java.lang.NullPointerException
	at gobblin.util.JobConfigurationUtils.putPropertiesIntoConfiguration(JobConfigurationUtils.java:62)
	at gobblin.runtime.mapreduce.MRJobLauncher.<init>(MRJobLauncher.java:134)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.<init>(CliMRJobLauncher.java:56)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)

it seems that can not get hadoop conf.

  Does someone else  has the same problem?

**Comment by lbendig** [comment]
https://github.com/linkedin/gobblin/pull/859 is intended to fix this issue, but it's not merged to the upstream yet.

**Comment by sahilTakiar** [comment]
#859 has been merged, please upgrade to the latest version and the bug should be fixed
