### ISSUE TITLE
java.io.IOException: Connection reset by peer

### ISSUE THREAD

**Issue by hegu8** [linkedin/gobblin#866]
I know this might be a Hadoop issue but since we are running other MR jobs on the same cluster and we are not seeing this problem so I think it might be more of a Gobblin issue.

So I configured my job to be ran in MapReduce mode, the job runs fine on my local standalone Hadoop cluster, but when it runs on the production cluster I got this exception (from the container log):

```
2016-03-17 23:56:24,490 INFO [Thread-282] org.apache.hadoop.hdfs.DFSClient: Exception in createBlockOutputStream
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:384)
	at org.apache.hadoop.net.SocketInputStream$Reader.performIO(SocketInputStream.java:57)
	at org.apache.hadoop.net.SocketIOWithTimeout.doIO(SocketIOWithTimeout.java:142)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:161)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:131)
	at org.apache.hadoop.net.SocketInputStream.read(SocketInputStream.java:118)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at java.io.FilterInputStream.read(FilterInputStream.java:83)
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2201)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1439)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1361)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:588)
2016-03-17 23:56:24,492 INFO [Thread-282] org.apache.hadoop.hdfs.DFSClient: Abandoning BP-409375033-10.0.6.18-1386712064969:blk_1077816944_4077812
2016-03-17 23:56:24,499 INFO [Thread-282] org.apache.hadoop.hdfs.DFSClient: Excluding datanode 10.0.6.139:50010
```

Then, it goes on to this one:

```
2016-03-17 23:56:24,865 INFO [Thread-288] org.apache.hadoop.hdfs.DFSClient: Exception in createBlockOutputStream
java.io.EOFException: Premature EOF: no length prefix available
	at org.apache.hadoop.hdfs.protocolPB.PBHelper.vintPrefixed(PBHelper.java:2203)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.createBlockOutputStream(DFSOutputStream.java:1439)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.nextBlockOutputStream(DFSOutputStream.java:1361)
	at org.apache.hadoop.hdfs.DFSOutputStream$DataStreamer.run(DFSOutputStream.java:588)
2016-03-17 23:56:24,865 INFO [Thread-288] org.apache.hadoop.hdfs.DFSClient: Abandoning BP-409375033-10.0.6.18-1386712064969:blk_1077816976_4077844
2016-03-17 23:56:24,867 INFO [Thread-288] org.apache.hadoop.hdfs.DFSClient: Excluding datanode 10.0.6.139:50010
```

At first I thought I might be using the wrong Hadoop host name, then I set the correct name at all possible places (gobblin-mapreduce.properties, --fs of gobblin-mapreduce.sh, and my job config), but it doesn't solve the problem. Anyone has seen this before?

**Comment by sahilTakiar** [comment]
hey @hegu8 could you provide us with a full copy of the logs? Is this consistently happening or is it intermittent? Does it always occur during a certain phase of the job?

**Comment by hegu8** [comment]
I just solve the problem. So this problem happens when I'm deploying the job for the first time ever on production, and I have `bootstrap.with.offset=earlest` so the job tries to pull everything from Kafka, which seems to create too many files and exhaust the blocks (just my guess), I set it to `latest` to bootstrap the offset and set it back to `earlest` again, and it worked perfectly.
