### ISSUE TITLE
4 Docker ---Hadoop and Kafka and Zookeeper and gobblin

### ISSUE THREAD

**Issue by jesusvillagra** [linkedin/gobblin#905]
I have installed hadoop in a Docker container, zookeeper in a Docker container, Kafka in another a Docker container, and gobblin in another a Docker container, because i want to record Kafka topics in hadoop, I've got connect gobblin with hadoop, but when i launch the mapreduce process to read kafka topics and write these in hadoop, I can´t. Kafka with zookeeper run ok. Gobblin with hadoop run ok, When i launched mapreduce wrote in hdfs the directires indicated in metrics.log.dir,  state.store.dir and mr.job.root.dir but didnt write data.publisher.final.dir

when i lanched 
$GOBBLIN_HOME/bin/gobblin-mapreduce.sh --conf $GOBBLIN_WORK_DIR/gobblin-etur.pull --jars $GOBBLIN_HOME/lib/*.jar,$KAFKA_HOME/libs/*.*

i obtened this error
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/gobblin-dist/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/hadoop/share/hadoop/common/lib/slf4j-log4j12-1.7.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Exception in thread "main" java.io.IOException: java.net.ConnectException: Call From 39c237e0d2ad/172.17.0.5 to 0.0.0.0:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:343)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobStatus(ClientServiceDelegate.java:428)
	at org.apache.hadoop.mapred.YARNRunner.getJobStatus(YARNRunner.java:572)
	at org.apache.hadoop.mapreduce.Job$1.run(Job.java:323)
	at org.apache.hadoop.mapreduce.Job$1.run(Job.java:320)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.mapreduce.Job.updateStatus(Job.java:320)
	at org.apache.hadoop.mapreduce.Job.isComplete(Job.java:604)
	at gobblin.runtime.mapreduce.MRJobLauncher.close(MRJobLauncher.java:175)
	at com.google.common.io.Closer.close(Closer.java:214)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.close(CliMRJobLauncher.java:97)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:69)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:221)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
Caused by: java.net.ConnectException: Call From 39c237e0d2ad/172.17.0.5 to 0.0.0.0:10020 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:792)
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:732)
	at org.apache.hadoop.ipc.Client.call(Client.java:1479)
	at org.apache.hadoop.ipc.Client.call(Client.java:1412)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy18.getJobReport(Unknown Source)
	at org.apache.hadoop.mapreduce.v2.api.impl.pb.client.MRClientProtocolPBClientImpl.getJobReport(MRClientProtocolPBClientImpl.java:133)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.mapred.ClientServiceDelegate.invoke(ClientServiceDelegate.java:324)
	... 22 more
Caused by: java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:531)
	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:495)
	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:614)
	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:712)
	at org.apache.hadoop.ipc.Client$Connection.access$2900(Client.java:375)
	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1528)
	at org.apache.hadoop.ipc.Client.call(Client.java:1451)
	... 30 more

This is my gobblin-etur.pull

# Directory where job locks are stored
job.lock.dir={{GOBBLIN_WORK_DIR}}/locks
job.name=GobblinKafkaQuickStart
job.group=GobblinKafka
job.description=Gobblin quick start job for Kafka
job.lock.enabled=false

# kafka
kafka.brokers={{KAFKA_ADVERTISED_HOST_NAME}}:{{KAFKA_PORT}}
source.class=gobblin.source.extractor.extract.kafka.KafkaSimpleSource
extract.namespace=gobblin.extract.kafka
topic.whitelist=Topic1
kafka.schema.registry.url=http://{{KAFKA_ADVERTISED_HOST_NAME}}:{{KAFKA_PORT}}

# File system URIs
fs.uri=hdfs://{{HADOOP_ADVERTISED_HOST_NAME}}
writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}

# Writer related configuration properties
writer.destination.type=HDFS
writer.output.format=txt
writer.staging.dir={{GOBBLIN_WORK_DIR}}/task-staging
writer.output.dir={{GOBBLIN_WORK_DIR}}/task-output
writer.builder.class=gobblin.writer.SimpleDataWriterBuilder
writer.file.path.type=tablename

# Data publisher related configuration properties
data.publisher.fs.uri=${fs.uri}
data.publisher.final.dir={{GOBBLIN_WORK_DIR}}/job-output
data.publisher.type=gobblin.publisher.BaseDataPublisher
data.publisher.replace.final.dir=false

# Directory where job/task state files are stored
state.store.dir={{GOBBLIN_WORK_DIR}}/state-store

# Directory where metrics log files are stored
metrics.log.dir={{GOBBLIN_WORK_DIR}}/metrics
metrics.reporting.file.enabled=true
metrics.reporting.file.suffix=txt

#Number of tasks to launch. In MR mode, this will be the number of mappers launched.
mr.job.max.mappers=1
mr.job.root.dir={{GOBBLIN_WORK_DIR}}/working
#For new topics / partitions, this property controls whether they start at the earliest offset or the latest offset. #Possible values: earliest, latest, skip
bootstrap.with.offset=earliest

task.data.root.dir={{GOBBLIN_WORK_DIR}}/task-data

These are my docker run

docker run -i -t --name hadoop  etur/hadoop:2.7.2

    Dockerfile
    VOLUME [ $HADOOP_INSTALL ]
    # HDFS ports
    EXPOSE 50070 50470 9000 50075 50475 50010 50020 50090

    # YARN ports
    EXPOSE 8088 8032 50060

docker run -d --name zookeeper etur/zookeeper:3.4.8 
    Dockerfile
    EXPOSE 2181 2888 3888
    VOLUME ["/opt/zookeeper"]

docker run --name kafka -e KAFKA_ADVERTISED_PORT=9092 -e KAFKA_BROKER_ID=1 -e KAFKA_ZOOKEEPER_CONNECT=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' zookeeper):2181  --link zookeeper:zookeeper -it etur/kafka:2.11-0.9.0.1 /bin/bash
   Dockerfile
   VOLUME [ $KAFKA_HOME ]
   EXPOSE 9092

docker run --name gobblin -e KAFKA_PORT=9092 -e KAFKA_ADVERTISED_HOST_NAME=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' kafka) -e HADOOP_ADVERTISED_HOST_NAME=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' hadoop):9000 -e HADOOP_BIN_DIR='/usr/local/hadoop/bin' --volumes-from  hadoop --volumes-from kafka --link kafka:kafka --link hadoop:hadoop -it etur/gobblin:0.6.2-327 -bash

Thanks

**Comment by sahilTakiar** [comment]
@jesusvillagra were you ever able to resolve this issue?
