### ISSUE TITLE
Throws the exception No enum constant org.apache.hadoop.mapreduce.JobCounter.NUM_CON_REL_TOTAL not every time

### ISSUE THREAD

**Issue by 492066199** [linkedin/gobblin#938]
hi dear,I pull data from kafka to hdfs,it catch the exception belows 
2016-04-23 00:13:39 CST ERROR [main] gobblin.runtime.AbstractJobLauncher  309 - Failed to launch and run job job_uvesubreqKafkaToHadoop_1461337234880: java.lang.IllegalArgumentException: No enum constant org.apache.hadoop.mapreduce.JobCounter.NUM_CON_REL_TOTAL
java.lang.IllegalArgumentException: No enum constant org.apache.hadoop.mapreduce.JobCounter.NUM_CON_REL_TOTAL
	at java.lang.Enum.valueOf(Enum.java:236)
	at org.apache.hadoop.mapreduce.counters.FrameworkCounterGroup.valueOf(FrameworkCounterGroup.java:148)
	at org.apache.hadoop.mapreduce.counters.FrameworkCounterGroup.findCounter(FrameworkCounterGroup.java:182)
	at org.apache.hadoop.mapreduce.counters.AbstractCounters.findCounter(AbstractCounters.java:154)
	at org.apache.hadoop.mapreduce.TypeConverter.fromYarn(TypeConverter.java:241)
	at org.apache.hadoop.mapred.ClientServiceDelegate.getJobCounters(ClientServiceDelegate.java:373)
	at org.apache.hadoop.mapred.YARNRunner.getJobCounters(YARNRunner.java:533)
	at org.apache.hadoop.mapreduce.Job$7.run(Job.java:756)
	at org.apache.hadoop.mapreduce.Job$7.run(Job.java:753)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:415)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
	at org.apache.hadoop.mapreduce.Job.getCounters(Job.java:753)
	at org.apache.hadoop.mapreduce.Job.monitorAndPrintJob(Job.java:1378)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1306)
	at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:209)
	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:285)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.launchJob(CliMRJobLauncher.java:87)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.run(CliMRJobLauncher.java:64)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at gobblin.runtime.mapreduce.CliMRJobLauncher.main(CliMRJobLauncher.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
Environment(hadoop 2.4)
I build gobblin with the hadoop 2.4,our production hadoop version is hadoop 2.4.
the error throws not every time,if I run goblin tasks 20 times, only throws the exception one time.
help me to solve it,thank you very much!

**Comment by sahilTakiar** [comment]
This seems to be related to: https://issues.apache.org/jira/browse/MAPREDUCE-5831 which says there are some incompatibilities between minor version of Hadoop 2.x.x

I suspect that for some reason a Hadoop version that is not 2.4 is getting put on the classpath of the Gobblin job, which also explains why this issue is intermittent.

I would adding `-PexcludeHadoopDeps` and `-PexcludeHiveDeps` to you Gradle build command (ref: http://gobblin.readthedocs.org/en/latest/user-guide/Gobblin-Build-Options/). That should fix the issue.
